/*
 * flyquery
 * Operational Structured-Data Intelligence (upload-driven) -- multi-tenant ingestion + Text-to-SQL over user-uploaded structured files (CSV / TSV / XLSX / XLS / ODS / JSON / JSONL / Parquet / Avro / ORC / Arrow / Feather + .gz/.zip/.bz2 variants). Materialises uploads to Parquet on object storage; indexes a long-lived schema knowledge base; answers natural-language questions via a multi-agent pipeline. Part of Firefly OperationOS.
 *
 * The version of the OpenAPI document: 26.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firefly.flyquery.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * LLM usage + cost for a single pipeline stage.  Surfaced inside :class:&#x60;UsageSummary&#x60; so callers see exactly where the tokens went. &#x60;&#x60;cost_usd&#x60;&#x60; is computed by the fireflyframework-agentic cost tracker (per-model rate table).
 */
@JsonPropertyOrder({
  AgentUsage.JSON_PROPERTY_AGENT,
  AgentUsage.JSON_PROPERTY_CALLS,
  AgentUsage.JSON_PROPERTY_COST_USD,
  AgentUsage.JSON_PROPERTY_INPUT_TOKENS,
  AgentUsage.JSON_PROPERTY_LATENCY_MS,
  AgentUsage.JSON_PROPERTY_MODEL,
  AgentUsage.JSON_PROPERTY_OUTPUT_TOKENS,
  AgentUsage.JSON_PROPERTY_TOTAL_TOKENS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-01T11:28:27.907207+02:00[Europe/Madrid]", comments = "Generator version: 7.22.0")
public class AgentUsage {
  public static final String JSON_PROPERTY_AGENT = "agent";
  @jakarta.annotation.Nonnull
  private String agent;

  public static final String JSON_PROPERTY_CALLS = "calls";
  @jakarta.annotation.Nullable
  private Integer calls = 0;

  public static final String JSON_PROPERTY_COST_USD = "cost_usd";
  @jakarta.annotation.Nullable
  private BigDecimal costUsd = new BigDecimal("0.0");

  public static final String JSON_PROPERTY_INPUT_TOKENS = "input_tokens";
  @jakarta.annotation.Nullable
  private Integer inputTokens = 0;

  public static final String JSON_PROPERTY_LATENCY_MS = "latency_ms";
  @jakarta.annotation.Nullable
  private BigDecimal latencyMs = new BigDecimal("0.0");

  public static final String JSON_PROPERTY_MODEL = "model";
  @jakarta.annotation.Nullable
  private JsonNullable<String> model = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_OUTPUT_TOKENS = "output_tokens";
  @jakarta.annotation.Nullable
  private Integer outputTokens = 0;

  public static final String JSON_PROPERTY_TOTAL_TOKENS = "total_tokens";
  @jakarta.annotation.Nullable
  private Integer totalTokens = 0;

  public AgentUsage() {
  }

  public AgentUsage agent(@jakarta.annotation.Nonnull String agent) {
    
    this.agent = agent;
    return this;
  }

  /**
   * Get agent
   * @return agent
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AGENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAgent() {
    return agent;
  }


  @JsonProperty(value = JSON_PROPERTY_AGENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAgent(@jakarta.annotation.Nonnull String agent) {
    this.agent = agent;
  }

  public AgentUsage calls(@jakarta.annotation.Nullable Integer calls) {
    
    this.calls = calls;
    return this;
  }

  /**
   * Get calls
   * @return calls
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CALLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCalls() {
    return calls;
  }


  @JsonProperty(value = JSON_PROPERTY_CALLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCalls(@jakarta.annotation.Nullable Integer calls) {
    this.calls = calls;
  }

  public AgentUsage costUsd(@jakarta.annotation.Nullable BigDecimal costUsd) {
    
    this.costUsd = costUsd;
    return this;
  }

  /**
   * Get costUsd
   * @return costUsd
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COST_USD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getCostUsd() {
    return costUsd;
  }


  @JsonProperty(value = JSON_PROPERTY_COST_USD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCostUsd(@jakarta.annotation.Nullable BigDecimal costUsd) {
    this.costUsd = costUsd;
  }

  public AgentUsage inputTokens(@jakarta.annotation.Nullable Integer inputTokens) {
    
    this.inputTokens = inputTokens;
    return this;
  }

  /**
   * Get inputTokens
   * @return inputTokens
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INPUT_TOKENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getInputTokens() {
    return inputTokens;
  }


  @JsonProperty(value = JSON_PROPERTY_INPUT_TOKENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInputTokens(@jakarta.annotation.Nullable Integer inputTokens) {
    this.inputTokens = inputTokens;
  }

  public AgentUsage latencyMs(@jakarta.annotation.Nullable BigDecimal latencyMs) {
    
    this.latencyMs = latencyMs;
    return this;
  }

  /**
   * Get latencyMs
   * @return latencyMs
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LATENCY_MS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getLatencyMs() {
    return latencyMs;
  }


  @JsonProperty(value = JSON_PROPERTY_LATENCY_MS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatencyMs(@jakarta.annotation.Nullable BigDecimal latencyMs) {
    this.latencyMs = latencyMs;
  }

  public AgentUsage model(@jakarta.annotation.Nullable String model) {
    this.model = JsonNullable.<String>of(model);
    
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getModel() {
        return model.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_MODEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getModel_JsonNullable() {
    return model;
  }
  
  @JsonProperty(JSON_PROPERTY_MODEL)
  public void setModel_JsonNullable(JsonNullable<String> model) {
    this.model = model;
  }

  public void setModel(@jakarta.annotation.Nullable String model) {
    this.model = JsonNullable.<String>of(model);
  }

  public AgentUsage outputTokens(@jakarta.annotation.Nullable Integer outputTokens) {
    
    this.outputTokens = outputTokens;
    return this;
  }

  /**
   * Get outputTokens
   * @return outputTokens
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OUTPUT_TOKENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOutputTokens() {
    return outputTokens;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTPUT_TOKENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOutputTokens(@jakarta.annotation.Nullable Integer outputTokens) {
    this.outputTokens = outputTokens;
  }

  public AgentUsage totalTokens(@jakarta.annotation.Nullable Integer totalTokens) {
    
    this.totalTokens = totalTokens;
    return this;
  }

  /**
   * Get totalTokens
   * @return totalTokens
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_TOKENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalTokens() {
    return totalTokens;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_TOKENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalTokens(@jakarta.annotation.Nullable Integer totalTokens) {
    this.totalTokens = totalTokens;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgentUsage agentUsage = (AgentUsage) o;
    return Objects.equals(this.agent, agentUsage.agent) &&
        Objects.equals(this.calls, agentUsage.calls) &&
        Objects.equals(this.costUsd, agentUsage.costUsd) &&
        Objects.equals(this.inputTokens, agentUsage.inputTokens) &&
        Objects.equals(this.latencyMs, agentUsage.latencyMs) &&
        equalsNullable(this.model, agentUsage.model) &&
        Objects.equals(this.outputTokens, agentUsage.outputTokens) &&
        Objects.equals(this.totalTokens, agentUsage.totalTokens);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(agent, calls, costUsd, inputTokens, latencyMs, hashCodeNullable(model), outputTokens, totalTokens);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgentUsage {\n");
    sb.append("    agent: ").append(toIndentedString(agent)).append("\n");
    sb.append("    calls: ").append(toIndentedString(calls)).append("\n");
    sb.append("    costUsd: ").append(toIndentedString(costUsd)).append("\n");
    sb.append("    inputTokens: ").append(toIndentedString(inputTokens)).append("\n");
    sb.append("    latencyMs: ").append(toIndentedString(latencyMs)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    outputTokens: ").append(toIndentedString(outputTokens)).append("\n");
    sb.append("    totalTokens: ").append(toIndentedString(totalTokens)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

