/*
 * flyquery
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 26.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firefly.flyquery.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.firefly.flyquery.model.ClarificationFrame;
import com.firefly.flyquery.model.UsageSummary;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Response from POST /api/v1/query (sync).
 */
@JsonPropertyOrder({
  AnswerResponse.JSON_PROPERTY_CHART_HINT,
  AnswerResponse.JSON_PROPERTY_CLARIFICATION,
  AnswerResponse.JSON_PROPERTY_ELAPSED_MS,
  AnswerResponse.JSON_PROPERTY_EXECUTION_STATUS,
  AnswerResponse.JSON_PROPERTY_EXPLANATION,
  AnswerResponse.JSON_PROPERTY_GROUNDED_SUMMARY,
  AnswerResponse.JSON_PROPERTY_PREVIEW,
  AnswerResponse.JSON_PROPERTY_QUERY_ID,
  AnswerResponse.JSON_PROPERTY_ROW_COUNT,
  AnswerResponse.JSON_PROPERTY_SNAPSHOT_PINS,
  AnswerResponse.JSON_PROPERTY_SQL,
  AnswerResponse.JSON_PROPERTY_TRUNCATED,
  AnswerResponse.JSON_PROPERTY_USAGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-24T00:36:39.059958+02:00[Europe/Madrid]", comments = "Generator version: 7.22.0")
public class AnswerResponse {
  /**
   * Gets or Sets chartHint
   */
  public enum ChartHintEnum {
    LINE(String.valueOf("line")),
    
    BAR(String.valueOf("bar")),
    
    TABLE(String.valueOf("table")),
    
    PIE(String.valueOf("pie")),
    
    NONE(String.valueOf("none"));

    private String value;

    ChartHintEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ChartHintEnum fromValue(String value) {
      for (ChartHintEnum b : ChartHintEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_CHART_HINT = "chart_hint";
  @javax.annotation.Nullable
  private JsonNullable<ChartHintEnum> chartHint = JsonNullable.<ChartHintEnum>undefined();

  public static final String JSON_PROPERTY_CLARIFICATION = "clarification";
  @javax.annotation.Nullable
  private JsonNullable<ClarificationFrame> clarification = JsonNullable.<ClarificationFrame>undefined();

  public static final String JSON_PROPERTY_ELAPSED_MS = "elapsed_ms";
  @javax.annotation.Nullable
  private Integer elapsedMs;

  /**
   * Gets or Sets executionStatus
   */
  public enum ExecutionStatusEnum {
    OK(String.valueOf("OK")),
    
    REFINED_OK(String.valueOf("REFINED_OK")),
    
    FAILED(String.valueOf("FAILED")),
    
    REJECTED_BY_FIREWALL(String.valueOf("REJECTED_BY_FIREWALL"));

    private String value;

    ExecutionStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ExecutionStatusEnum fromValue(String value) {
      for (ExecutionStatusEnum b : ExecutionStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_EXECUTION_STATUS = "execution_status";
  @javax.annotation.Nullable
  private ExecutionStatusEnum executionStatus;

  public static final String JSON_PROPERTY_EXPLANATION = "explanation";
  @javax.annotation.Nullable
  private JsonNullable<String> explanation = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_GROUNDED_SUMMARY = "grounded_summary";
  @javax.annotation.Nullable
  private JsonNullable<Map<String, Object>> groundedSummary = JsonNullable.<Map<String, Object>>undefined();

  public static final String JSON_PROPERTY_PREVIEW = "preview";
  @javax.annotation.Nullable
  private List<Map<String, Object>> preview;

  public static final String JSON_PROPERTY_QUERY_ID = "query_id";
  @javax.annotation.Nonnull
  private UUID queryId;

  public static final String JSON_PROPERTY_ROW_COUNT = "row_count";
  @javax.annotation.Nullable
  private Integer rowCount;

  public static final String JSON_PROPERTY_SNAPSHOT_PINS = "snapshot_pins";
  @javax.annotation.Nullable
  private Map<String, String> snapshotPins = new HashMap<>();

  public static final String JSON_PROPERTY_SQL = "sql";
  @javax.annotation.Nullable
  private String sql;

  public static final String JSON_PROPERTY_TRUNCATED = "truncated";
  @javax.annotation.Nullable
  private Boolean truncated = false;

  public static final String JSON_PROPERTY_USAGE = "usage";
  @javax.annotation.Nullable
  private JsonNullable<UsageSummary> usage = JsonNullable.<UsageSummary>undefined();

  public AnswerResponse() {
  }

  public AnswerResponse chartHint(@javax.annotation.Nullable ChartHintEnum chartHint) {
    this.chartHint = JsonNullable.<ChartHintEnum>of(chartHint);
    
    return this;
  }

  /**
   * Get chartHint
   * @return chartHint
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public ChartHintEnum getChartHint() {
        return chartHint.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CHART_HINT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<ChartHintEnum> getChartHint_JsonNullable() {
    return chartHint;
  }
  
  @JsonProperty(JSON_PROPERTY_CHART_HINT)
  public void setChartHint_JsonNullable(JsonNullable<ChartHintEnum> chartHint) {
    this.chartHint = chartHint;
  }

  public void setChartHint(@javax.annotation.Nullable ChartHintEnum chartHint) {
    this.chartHint = JsonNullable.<ChartHintEnum>of(chartHint);
  }

  public AnswerResponse clarification(@javax.annotation.Nullable ClarificationFrame clarification) {
    this.clarification = JsonNullable.<ClarificationFrame>of(clarification);
    
    return this;
  }

  /**
   * Get clarification
   * @return clarification
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public ClarificationFrame getClarification() {
        return clarification.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CLARIFICATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<ClarificationFrame> getClarification_JsonNullable() {
    return clarification;
  }
  
  @JsonProperty(JSON_PROPERTY_CLARIFICATION)
  public void setClarification_JsonNullable(JsonNullable<ClarificationFrame> clarification) {
    this.clarification = clarification;
  }

  public void setClarification(@javax.annotation.Nullable ClarificationFrame clarification) {
    this.clarification = JsonNullable.<ClarificationFrame>of(clarification);
  }

  public AnswerResponse elapsedMs(@javax.annotation.Nullable Integer elapsedMs) {
    
    this.elapsedMs = elapsedMs;
    return this;
  }

  /**
   * Get elapsedMs
   * @return elapsedMs
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ELAPSED_MS, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getElapsedMs() {
    return elapsedMs;
  }


  @JsonProperty(value = JSON_PROPERTY_ELAPSED_MS, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setElapsedMs(@javax.annotation.Nullable Integer elapsedMs) {
    this.elapsedMs = elapsedMs;
  }

  public AnswerResponse executionStatus(@javax.annotation.Nullable ExecutionStatusEnum executionStatus) {
    
    this.executionStatus = executionStatus;
    return this;
  }

  /**
   * Get executionStatus
   * @return executionStatus
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXECUTION_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ExecutionStatusEnum getExecutionStatus() {
    return executionStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_EXECUTION_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExecutionStatus(@javax.annotation.Nullable ExecutionStatusEnum executionStatus) {
    this.executionStatus = executionStatus;
  }

  public AnswerResponse explanation(@javax.annotation.Nullable String explanation) {
    this.explanation = JsonNullable.<String>of(explanation);
    
    return this;
  }

  /**
   * Get explanation
   * @return explanation
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getExplanation() {
        return explanation.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_EXPLANATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getExplanation_JsonNullable() {
    return explanation;
  }
  
  @JsonProperty(JSON_PROPERTY_EXPLANATION)
  public void setExplanation_JsonNullable(JsonNullable<String> explanation) {
    this.explanation = explanation;
  }

  public void setExplanation(@javax.annotation.Nullable String explanation) {
    this.explanation = JsonNullable.<String>of(explanation);
  }

  public AnswerResponse groundedSummary(@javax.annotation.Nullable Map<String, Object> groundedSummary) {
    this.groundedSummary = JsonNullable.<Map<String, Object>>of(groundedSummary);
    
    return this;
  }

  public AnswerResponse putGroundedSummaryItem(String key, Object groundedSummaryItem) {
    if (this.groundedSummary == null || !this.groundedSummary.isPresent()) {
      this.groundedSummary = JsonNullable.<Map<String, Object>>of(new HashMap<>());
    }
    try {
      this.groundedSummary.get().put(key, groundedSummaryItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get groundedSummary
   * @return groundedSummary
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Map<String, Object> getGroundedSummary() {
        return groundedSummary.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_GROUNDED_SUMMARY, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, Object>> getGroundedSummary_JsonNullable() {
    return groundedSummary;
  }
  
  @JsonProperty(JSON_PROPERTY_GROUNDED_SUMMARY)
  public void setGroundedSummary_JsonNullable(JsonNullable<Map<String, Object>> groundedSummary) {
    this.groundedSummary = groundedSummary;
  }

  public void setGroundedSummary(@javax.annotation.Nullable Map<String, Object> groundedSummary) {
    this.groundedSummary = JsonNullable.<Map<String, Object>>of(groundedSummary);
  }

  public AnswerResponse preview(@javax.annotation.Nullable List<Map<String, Object>> preview) {
    
    this.preview = preview;
    return this;
  }

  public AnswerResponse addPreviewItem(Map<String, Object> previewItem) {
    if (this.preview == null) {
      this.preview = new ArrayList<>();
    }
    this.preview.add(previewItem);
    return this;
  }

  /**
   * Get preview
   * @return preview
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREVIEW, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Map<String, Object>> getPreview() {
    return preview;
  }


  @JsonProperty(value = JSON_PROPERTY_PREVIEW, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPreview(@javax.annotation.Nullable List<Map<String, Object>> preview) {
    this.preview = preview;
  }

  public AnswerResponse queryId(@javax.annotation.Nonnull UUID queryId) {
    
    this.queryId = queryId;
    return this;
  }

  /**
   * Get queryId
   * @return queryId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_QUERY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getQueryId() {
    return queryId;
  }


  @JsonProperty(value = JSON_PROPERTY_QUERY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQueryId(@javax.annotation.Nonnull UUID queryId) {
    this.queryId = queryId;
  }

  public AnswerResponse rowCount(@javax.annotation.Nullable Integer rowCount) {
    
    this.rowCount = rowCount;
    return this;
  }

  /**
   * Get rowCount
   * @return rowCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ROW_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getRowCount() {
    return rowCount;
  }


  @JsonProperty(value = JSON_PROPERTY_ROW_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRowCount(@javax.annotation.Nullable Integer rowCount) {
    this.rowCount = rowCount;
  }

  public AnswerResponse snapshotPins(@javax.annotation.Nullable Map<String, String> snapshotPins) {
    
    this.snapshotPins = snapshotPins;
    return this;
  }

  public AnswerResponse putSnapshotPinsItem(String key, String snapshotPinsItem) {
    if (this.snapshotPins == null) {
      this.snapshotPins = new HashMap<>();
    }
    this.snapshotPins.put(key, snapshotPinsItem);
    return this;
  }

  /**
   * Get snapshotPins
   * @return snapshotPins
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SNAPSHOT_PINS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getSnapshotPins() {
    return snapshotPins;
  }


  @JsonProperty(value = JSON_PROPERTY_SNAPSHOT_PINS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSnapshotPins(@javax.annotation.Nullable Map<String, String> snapshotPins) {
    this.snapshotPins = snapshotPins;
  }

  public AnswerResponse sql(@javax.annotation.Nullable String sql) {
    
    this.sql = sql;
    return this;
  }

  /**
   * Get sql
   * @return sql
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SQL, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSql() {
    return sql;
  }


  @JsonProperty(value = JSON_PROPERTY_SQL, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSql(@javax.annotation.Nullable String sql) {
    this.sql = sql;
  }

  public AnswerResponse truncated(@javax.annotation.Nullable Boolean truncated) {
    
    this.truncated = truncated;
    return this;
  }

  /**
   * Get truncated
   * @return truncated
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRUNCATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTruncated() {
    return truncated;
  }


  @JsonProperty(value = JSON_PROPERTY_TRUNCATED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTruncated(@javax.annotation.Nullable Boolean truncated) {
    this.truncated = truncated;
  }

  public AnswerResponse usage(@javax.annotation.Nullable UsageSummary usage) {
    this.usage = JsonNullable.<UsageSummary>of(usage);
    
    return this;
  }

  /**
   * Get usage
   * @return usage
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public UsageSummary getUsage() {
        return usage.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_USAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<UsageSummary> getUsage_JsonNullable() {
    return usage;
  }
  
  @JsonProperty(JSON_PROPERTY_USAGE)
  public void setUsage_JsonNullable(JsonNullable<UsageSummary> usage) {
    this.usage = usage;
  }

  public void setUsage(@javax.annotation.Nullable UsageSummary usage) {
    this.usage = JsonNullable.<UsageSummary>of(usage);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnswerResponse answerResponse = (AnswerResponse) o;
    return equalsNullable(this.chartHint, answerResponse.chartHint) &&
        equalsNullable(this.clarification, answerResponse.clarification) &&
        Objects.equals(this.elapsedMs, answerResponse.elapsedMs) &&
        Objects.equals(this.executionStatus, answerResponse.executionStatus) &&
        equalsNullable(this.explanation, answerResponse.explanation) &&
        equalsNullable(this.groundedSummary, answerResponse.groundedSummary) &&
        Objects.equals(this.preview, answerResponse.preview) &&
        Objects.equals(this.queryId, answerResponse.queryId) &&
        Objects.equals(this.rowCount, answerResponse.rowCount) &&
        Objects.equals(this.snapshotPins, answerResponse.snapshotPins) &&
        Objects.equals(this.sql, answerResponse.sql) &&
        Objects.equals(this.truncated, answerResponse.truncated) &&
        equalsNullable(this.usage, answerResponse.usage);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(chartHint), hashCodeNullable(clarification), elapsedMs, executionStatus, hashCodeNullable(explanation), hashCodeNullable(groundedSummary), preview, queryId, rowCount, snapshotPins, sql, truncated, hashCodeNullable(usage));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnswerResponse {\n");
    sb.append("    chartHint: ").append(toIndentedString(chartHint)).append("\n");
    sb.append("    clarification: ").append(toIndentedString(clarification)).append("\n");
    sb.append("    elapsedMs: ").append(toIndentedString(elapsedMs)).append("\n");
    sb.append("    executionStatus: ").append(toIndentedString(executionStatus)).append("\n");
    sb.append("    explanation: ").append(toIndentedString(explanation)).append("\n");
    sb.append("    groundedSummary: ").append(toIndentedString(groundedSummary)).append("\n");
    sb.append("    preview: ").append(toIndentedString(preview)).append("\n");
    sb.append("    queryId: ").append(toIndentedString(queryId)).append("\n");
    sb.append("    rowCount: ").append(toIndentedString(rowCount)).append("\n");
    sb.append("    snapshotPins: ").append(toIndentedString(snapshotPins)).append("\n");
    sb.append("    sql: ").append(toIndentedString(sql)).append("\n");
    sb.append("    truncated: ").append(toIndentedString(truncated)).append("\n");
    sb.append("    usage: ").append(toIndentedString(usage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

