/*
 * flyquery
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 26.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firefly.flyquery.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.firefly.flyquery.model.ClarificationFrame;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Response from POST /api/v1/query:explain — Grounding + Generation only.
 */
@JsonPropertyOrder({
  ExplainResponse.JSON_PROPERTY_CLARIFICATION,
  ExplainResponse.JSON_PROPERTY_CONFIDENCE,
  ExplainResponse.JSON_PROPERTY_GROUNDED_SUMMARY,
  ExplainResponse.JSON_PROPERTY_REASONING,
  ExplainResponse.JSON_PROPERTY_SQL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-24T00:36:39.059958+02:00[Europe/Madrid]", comments = "Generator version: 7.22.0")
public class ExplainResponse {
  public static final String JSON_PROPERTY_CLARIFICATION = "clarification";
  @javax.annotation.Nullable
  private JsonNullable<ClarificationFrame> clarification = JsonNullable.<ClarificationFrame>undefined();

  public static final String JSON_PROPERTY_CONFIDENCE = "confidence";
  @javax.annotation.Nullable
  private BigDecimal confidence;

  public static final String JSON_PROPERTY_GROUNDED_SUMMARY = "grounded_summary";
  @javax.annotation.Nullable
  private JsonNullable<Map<String, Object>> groundedSummary = JsonNullable.<Map<String, Object>>undefined();

  public static final String JSON_PROPERTY_REASONING = "reasoning";
  @javax.annotation.Nullable
  private String reasoning;

  public static final String JSON_PROPERTY_SQL = "sql";
  @javax.annotation.Nullable
  private String sql;

  public ExplainResponse() {
  }

  public ExplainResponse clarification(@javax.annotation.Nullable ClarificationFrame clarification) {
    this.clarification = JsonNullable.<ClarificationFrame>of(clarification);
    
    return this;
  }

  /**
   * Get clarification
   * @return clarification
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public ClarificationFrame getClarification() {
        return clarification.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CLARIFICATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<ClarificationFrame> getClarification_JsonNullable() {
    return clarification;
  }
  
  @JsonProperty(JSON_PROPERTY_CLARIFICATION)
  public void setClarification_JsonNullable(JsonNullable<ClarificationFrame> clarification) {
    this.clarification = clarification;
  }

  public void setClarification(@javax.annotation.Nullable ClarificationFrame clarification) {
    this.clarification = JsonNullable.<ClarificationFrame>of(clarification);
  }

  public ExplainResponse confidence(@javax.annotation.Nullable BigDecimal confidence) {
    
    this.confidence = confidence;
    return this;
  }

  /**
   * Get confidence
   * @return confidence
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONFIDENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getConfidence() {
    return confidence;
  }


  @JsonProperty(value = JSON_PROPERTY_CONFIDENCE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConfidence(@javax.annotation.Nullable BigDecimal confidence) {
    this.confidence = confidence;
  }

  public ExplainResponse groundedSummary(@javax.annotation.Nullable Map<String, Object> groundedSummary) {
    this.groundedSummary = JsonNullable.<Map<String, Object>>of(groundedSummary);
    
    return this;
  }

  public ExplainResponse putGroundedSummaryItem(String key, Object groundedSummaryItem) {
    if (this.groundedSummary == null || !this.groundedSummary.isPresent()) {
      this.groundedSummary = JsonNullable.<Map<String, Object>>of(new HashMap<>());
    }
    try {
      this.groundedSummary.get().put(key, groundedSummaryItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get groundedSummary
   * @return groundedSummary
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Map<String, Object> getGroundedSummary() {
        return groundedSummary.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_GROUNDED_SUMMARY, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, Object>> getGroundedSummary_JsonNullable() {
    return groundedSummary;
  }
  
  @JsonProperty(JSON_PROPERTY_GROUNDED_SUMMARY)
  public void setGroundedSummary_JsonNullable(JsonNullable<Map<String, Object>> groundedSummary) {
    this.groundedSummary = groundedSummary;
  }

  public void setGroundedSummary(@javax.annotation.Nullable Map<String, Object> groundedSummary) {
    this.groundedSummary = JsonNullable.<Map<String, Object>>of(groundedSummary);
  }

  public ExplainResponse reasoning(@javax.annotation.Nullable String reasoning) {
    
    this.reasoning = reasoning;
    return this;
  }

  /**
   * Get reasoning
   * @return reasoning
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REASONING, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getReasoning() {
    return reasoning;
  }


  @JsonProperty(value = JSON_PROPERTY_REASONING, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReasoning(@javax.annotation.Nullable String reasoning) {
    this.reasoning = reasoning;
  }

  public ExplainResponse sql(@javax.annotation.Nullable String sql) {
    
    this.sql = sql;
    return this;
  }

  /**
   * Get sql
   * @return sql
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SQL, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSql() {
    return sql;
  }


  @JsonProperty(value = JSON_PROPERTY_SQL, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSql(@javax.annotation.Nullable String sql) {
    this.sql = sql;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExplainResponse explainResponse = (ExplainResponse) o;
    return equalsNullable(this.clarification, explainResponse.clarification) &&
        Objects.equals(this.confidence, explainResponse.confidence) &&
        equalsNullable(this.groundedSummary, explainResponse.groundedSummary) &&
        Objects.equals(this.reasoning, explainResponse.reasoning) &&
        Objects.equals(this.sql, explainResponse.sql);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(clarification), confidence, hashCodeNullable(groundedSummary), reasoning, sql);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExplainResponse {\n");
    sb.append("    clarification: ").append(toIndentedString(clarification)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("    groundedSummary: ").append(toIndentedString(groundedSummary)).append("\n");
    sb.append("    reasoning: ").append(toIndentedString(reasoning)).append("\n");
    sb.append("    sql: ").append(toIndentedString(sql)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

