/*
 * flyquery
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 26.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firefly.flyquery.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.firefly.flyquery.model.TableSummary;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Response from POST /datasets/{id}/files.
 */
@JsonPropertyOrder({
  FileUploadResponse.JSON_PROPERTY_FILE_ID,
  FileUploadResponse.JSON_PROPERTY_TABLES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-23T22:03:38.852419+02:00[Europe/Madrid]", comments = "Generator version: 7.22.0")
public class FileUploadResponse {
  public static final String JSON_PROPERTY_FILE_ID = "file_id";
  @javax.annotation.Nonnull
  private String fileId;

  public static final String JSON_PROPERTY_TABLES = "tables";
  @javax.annotation.Nonnull
  private List<TableSummary> tables = new ArrayList<>();

  public FileUploadResponse() {
  }

  public FileUploadResponse fileId(@javax.annotation.Nonnull String fileId) {
    
    this.fileId = fileId;
    return this;
  }

  /**
   * Get fileId
   * @return fileId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FILE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFileId() {
    return fileId;
  }


  @JsonProperty(value = JSON_PROPERTY_FILE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFileId(@javax.annotation.Nonnull String fileId) {
    this.fileId = fileId;
  }

  public FileUploadResponse tables(@javax.annotation.Nonnull List<TableSummary> tables) {
    
    this.tables = tables;
    return this;
  }

  public FileUploadResponse addTablesItem(TableSummary tablesItem) {
    if (this.tables == null) {
      this.tables = new ArrayList<>();
    }
    this.tables.add(tablesItem);
    return this;
  }

  /**
   * Get tables
   * @return tables
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TABLES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<TableSummary> getTables() {
    return tables;
  }


  @JsonProperty(value = JSON_PROPERTY_TABLES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTables(@javax.annotation.Nonnull List<TableSummary> tables) {
    this.tables = tables;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileUploadResponse fileUploadResponse = (FileUploadResponse) o;
    return Objects.equals(this.fileId, fileUploadResponse.fileId) &&
        Objects.equals(this.tables, fileUploadResponse.tables);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileId, tables);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileUploadResponse {\n");
    sb.append("    fileId: ").append(toIndentedString(fileId)).append("\n");
    sb.append("    tables: ").append(toIndentedString(tables)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

