/*
 * flyquery
 * Operational Structured-Data Intelligence (upload-driven) -- multi-tenant ingestion + Text-to-SQL over user-uploaded structured files (CSV / TSV / XLSX / XLS / ODS / JSON / JSONL / Parquet / Avro / ORC / Arrow / Feather + .gz/.zip/.bz2 variants). Materialises uploads to Parquet on object storage; indexes a long-lived schema knowledge base; answers natural-language questions via a multi-agent pipeline. Part of Firefly OperationOS.
 *
 * The version of the OpenAPI document: 26.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firefly.flyquery.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * One row from flyquery_ingest_events.
 */
@JsonPropertyOrder({
  IngestEventRead.JSON_PROPERTY_CREATED_AT,
  IngestEventRead.JSON_PROPERTY_ID,
  IngestEventRead.JSON_PROPERTY_INGEST_JOB_ID,
  IngestEventRead.JSON_PROPERTY_MESSAGE,
  IngestEventRead.JSON_PROPERTY_PAYLOAD_JSON,
  IngestEventRead.JSON_PROPERTY_STAGE,
  IngestEventRead.JSON_PROPERTY_STATUS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-24T14:41:07.623178+02:00[Europe/Madrid]", comments = "Generator version: 7.22.0")
public class IngestEventRead {
  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private Integer id;

  public static final String JSON_PROPERTY_INGEST_JOB_ID = "ingest_job_id";
  @jakarta.annotation.Nonnull
  private UUID ingestJobId;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nullable
  private String message;

  public static final String JSON_PROPERTY_PAYLOAD_JSON = "payload_json";
  @jakarta.annotation.Nonnull
  private Map<String, Object> payloadJson = new HashMap<>();

  public static final String JSON_PROPERTY_STAGE = "stage";
  @jakarta.annotation.Nonnull
  private String stage;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private String status;

  public IngestEventRead() {
  }

  public IngestEventRead createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public IngestEventRead id(@jakarta.annotation.Nonnull Integer id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull Integer id) {
    this.id = id;
  }

  public IngestEventRead ingestJobId(@jakarta.annotation.Nonnull UUID ingestJobId) {
    
    this.ingestJobId = ingestJobId;
    return this;
  }

  /**
   * Get ingestJobId
   * @return ingestJobId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INGEST_JOB_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getIngestJobId() {
    return ingestJobId;
  }


  @JsonProperty(value = JSON_PROPERTY_INGEST_JOB_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIngestJobId(@jakarta.annotation.Nonnull UUID ingestJobId) {
    this.ingestJobId = ingestJobId;
  }

  public IngestEventRead message(@jakarta.annotation.Nullable String message) {
    
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@jakarta.annotation.Nullable String message) {
    this.message = message;
  }

  public IngestEventRead payloadJson(@jakarta.annotation.Nonnull Map<String, Object> payloadJson) {
    
    this.payloadJson = payloadJson;
    return this;
  }

  public IngestEventRead putPayloadJsonItem(String key, Object payloadJsonItem) {
    this.payloadJson.put(key, payloadJsonItem);
    return this;
  }

  /**
   * Get payloadJson
   * @return payloadJson
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAYLOAD_JSON, required = true)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)

  public Map<String, Object> getPayloadJson() {
    return payloadJson;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYLOAD_JSON, required = true)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public void setPayloadJson(@jakarta.annotation.Nonnull Map<String, Object> payloadJson) {
    this.payloadJson = payloadJson;
  }

  public IngestEventRead stage(@jakarta.annotation.Nonnull String stage) {
    
    this.stage = stage;
    return this;
  }

  /**
   * Get stage
   * @return stage
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStage() {
    return stage;
  }


  @JsonProperty(value = JSON_PROPERTY_STAGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStage(@jakarta.annotation.Nonnull String stage) {
    this.stage = stage;
  }

  public IngestEventRead status(@jakarta.annotation.Nonnull String status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IngestEventRead ingestEventRead = (IngestEventRead) o;
    return Objects.equals(this.createdAt, ingestEventRead.createdAt) &&
        Objects.equals(this.id, ingestEventRead.id) &&
        Objects.equals(this.ingestJobId, ingestEventRead.ingestJobId) &&
        Objects.equals(this.message, ingestEventRead.message) &&
        Objects.equals(this.payloadJson, ingestEventRead.payloadJson) &&
        Objects.equals(this.stage, ingestEventRead.stage) &&
        Objects.equals(this.status, ingestEventRead.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, id, ingestJobId, message, payloadJson, stage, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IngestEventRead {\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ingestJobId: ").append(toIndentedString(ingestJobId)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    payloadJson: ").append(toIndentedString(payloadJson)).append("\n");
    sb.append("    stage: ").append(toIndentedString(stage)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

