/*
 * flyquery
 * Operational Structured-Data Intelligence (upload-driven) -- multi-tenant ingestion + Text-to-SQL over user-uploaded structured files (CSV / TSV / XLSX / XLS / ODS / JSON / JSONL / Parquet / Avro / ORC / Arrow / Feather + .gz/.zip/.bz2 variants). Materialises uploads to Parquet on object storage; indexes a long-lived schema knowledge base; answers natural-language questions via a multi-agent pipeline. Part of Firefly OperationOS.
 *
 * The version of the OpenAPI document: 26.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firefly.flyquery.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Response for GET /tables/{id}/changes items.
 */
@JsonPropertyOrder({
  SchemaChangeRead.JSON_PROPERTY_AFTER_JSON,
  SchemaChangeRead.JSON_PROPERTY_APPROVED_AT,
  SchemaChangeRead.JSON_PROPERTY_APPROVED_BY,
  SchemaChangeRead.JSON_PROPERTY_BEFORE_JSON,
  SchemaChangeRead.JSON_PROPERTY_CHANGE,
  SchemaChangeRead.JSON_PROPERTY_COLUMN_NAME,
  SchemaChangeRead.JSON_PROPERTY_CREATED_AT,
  SchemaChangeRead.JSON_PROPERTY_ID,
  SchemaChangeRead.JSON_PROPERTY_LLM_RATIONALE,
  SchemaChangeRead.JSON_PROPERTY_NEXT_SNAPSHOT_ID,
  SchemaChangeRead.JSON_PROPERTY_PREV_SNAPSHOT_ID,
  SchemaChangeRead.JSON_PROPERTY_TABLE_ID
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-01T11:28:27.907207+02:00[Europe/Madrid]", comments = "Generator version: 7.22.0")
public class SchemaChangeRead {
  public static final String JSON_PROPERTY_AFTER_JSON = "after_json";
  @jakarta.annotation.Nullable
  private Map<String, Object> afterJson;

  public static final String JSON_PROPERTY_APPROVED_AT = "approved_at";
  @jakarta.annotation.Nullable
  private JsonNullable<OffsetDateTime> approvedAt = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_APPROVED_BY = "approved_by";
  @jakarta.annotation.Nullable
  private JsonNullable<String> approvedBy = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_BEFORE_JSON = "before_json";
  @jakarta.annotation.Nullable
  private Map<String, Object> beforeJson;

  public static final String JSON_PROPERTY_CHANGE = "change";
  @jakarta.annotation.Nonnull
  private String change;

  public static final String JSON_PROPERTY_COLUMN_NAME = "column_name";
  @jakarta.annotation.Nonnull
  private String columnName;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_LLM_RATIONALE = "llm_rationale";
  @jakarta.annotation.Nullable
  private String llmRationale;

  public static final String JSON_PROPERTY_NEXT_SNAPSHOT_ID = "next_snapshot_id";
  @jakarta.annotation.Nonnull
  private UUID nextSnapshotId;

  public static final String JSON_PROPERTY_PREV_SNAPSHOT_ID = "prev_snapshot_id";
  @jakarta.annotation.Nullable
  private UUID prevSnapshotId;

  public static final String JSON_PROPERTY_TABLE_ID = "table_id";
  @jakarta.annotation.Nonnull
  private UUID tableId;

  public SchemaChangeRead() {
  }

  public SchemaChangeRead afterJson(@jakarta.annotation.Nullable Map<String, Object> afterJson) {
    
    this.afterJson = afterJson;
    return this;
  }

  public SchemaChangeRead putAfterJsonItem(String key, Object afterJsonItem) {
    this.afterJson.put(key, afterJsonItem);
    return this;
  }

  /**
   * Get afterJson
   * @return afterJson
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AFTER_JSON, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)

  public Map<String, Object> getAfterJson() {
    return afterJson;
  }


  @JsonProperty(value = JSON_PROPERTY_AFTER_JSON, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public void setAfterJson(@jakarta.annotation.Nullable Map<String, Object> afterJson) {
    this.afterJson = afterJson;
  }

  public SchemaChangeRead approvedAt(@jakarta.annotation.Nullable OffsetDateTime approvedAt) {
    this.approvedAt = JsonNullable.<OffsetDateTime>of(approvedAt);
    
    return this;
  }

  /**
   * Get approvedAt
   * @return approvedAt
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getApprovedAt() {
        return approvedAt.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_APPROVED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getApprovedAt_JsonNullable() {
    return approvedAt;
  }
  
  @JsonProperty(JSON_PROPERTY_APPROVED_AT)
  public void setApprovedAt_JsonNullable(JsonNullable<OffsetDateTime> approvedAt) {
    this.approvedAt = approvedAt;
  }

  public void setApprovedAt(@jakarta.annotation.Nullable OffsetDateTime approvedAt) {
    this.approvedAt = JsonNullable.<OffsetDateTime>of(approvedAt);
  }

  public SchemaChangeRead approvedBy(@jakarta.annotation.Nullable String approvedBy) {
    this.approvedBy = JsonNullable.<String>of(approvedBy);
    
    return this;
  }

  /**
   * Get approvedBy
   * @return approvedBy
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getApprovedBy() {
        return approvedBy.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_APPROVED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getApprovedBy_JsonNullable() {
    return approvedBy;
  }
  
  @JsonProperty(JSON_PROPERTY_APPROVED_BY)
  public void setApprovedBy_JsonNullable(JsonNullable<String> approvedBy) {
    this.approvedBy = approvedBy;
  }

  public void setApprovedBy(@jakarta.annotation.Nullable String approvedBy) {
    this.approvedBy = JsonNullable.<String>of(approvedBy);
  }

  public SchemaChangeRead beforeJson(@jakarta.annotation.Nullable Map<String, Object> beforeJson) {
    
    this.beforeJson = beforeJson;
    return this;
  }

  public SchemaChangeRead putBeforeJsonItem(String key, Object beforeJsonItem) {
    this.beforeJson.put(key, beforeJsonItem);
    return this;
  }

  /**
   * Get beforeJson
   * @return beforeJson
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BEFORE_JSON, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)

  public Map<String, Object> getBeforeJson() {
    return beforeJson;
  }


  @JsonProperty(value = JSON_PROPERTY_BEFORE_JSON, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public void setBeforeJson(@jakarta.annotation.Nullable Map<String, Object> beforeJson) {
    this.beforeJson = beforeJson;
  }

  public SchemaChangeRead change(@jakarta.annotation.Nonnull String change) {
    
    this.change = change;
    return this;
  }

  /**
   * Get change
   * @return change
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CHANGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getChange() {
    return change;
  }


  @JsonProperty(value = JSON_PROPERTY_CHANGE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChange(@jakarta.annotation.Nonnull String change) {
    this.change = change;
  }

  public SchemaChangeRead columnName(@jakarta.annotation.Nonnull String columnName) {
    
    this.columnName = columnName;
    return this;
  }

  /**
   * Get columnName
   * @return columnName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COLUMN_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getColumnName() {
    return columnName;
  }


  @JsonProperty(value = JSON_PROPERTY_COLUMN_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setColumnName(@jakarta.annotation.Nonnull String columnName) {
    this.columnName = columnName;
  }

  public SchemaChangeRead createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public SchemaChangeRead id(@jakarta.annotation.Nonnull UUID id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }

  public SchemaChangeRead llmRationale(@jakarta.annotation.Nullable String llmRationale) {
    
    this.llmRationale = llmRationale;
    return this;
  }

  /**
   * Get llmRationale
   * @return llmRationale
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LLM_RATIONALE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLlmRationale() {
    return llmRationale;
  }


  @JsonProperty(value = JSON_PROPERTY_LLM_RATIONALE, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLlmRationale(@jakarta.annotation.Nullable String llmRationale) {
    this.llmRationale = llmRationale;
  }

  public SchemaChangeRead nextSnapshotId(@jakarta.annotation.Nonnull UUID nextSnapshotId) {
    
    this.nextSnapshotId = nextSnapshotId;
    return this;
  }

  /**
   * Get nextSnapshotId
   * @return nextSnapshotId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NEXT_SNAPSHOT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getNextSnapshotId() {
    return nextSnapshotId;
  }


  @JsonProperty(value = JSON_PROPERTY_NEXT_SNAPSHOT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNextSnapshotId(@jakarta.annotation.Nonnull UUID nextSnapshotId) {
    this.nextSnapshotId = nextSnapshotId;
  }

  public SchemaChangeRead prevSnapshotId(@jakarta.annotation.Nullable UUID prevSnapshotId) {
    
    this.prevSnapshotId = prevSnapshotId;
    return this;
  }

  /**
   * Get prevSnapshotId
   * @return prevSnapshotId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PREV_SNAPSHOT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getPrevSnapshotId() {
    return prevSnapshotId;
  }


  @JsonProperty(value = JSON_PROPERTY_PREV_SNAPSHOT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrevSnapshotId(@jakarta.annotation.Nullable UUID prevSnapshotId) {
    this.prevSnapshotId = prevSnapshotId;
  }

  public SchemaChangeRead tableId(@jakarta.annotation.Nonnull UUID tableId) {
    
    this.tableId = tableId;
    return this;
  }

  /**
   * Get tableId
   * @return tableId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TABLE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getTableId() {
    return tableId;
  }


  @JsonProperty(value = JSON_PROPERTY_TABLE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTableId(@jakarta.annotation.Nonnull UUID tableId) {
    this.tableId = tableId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SchemaChangeRead schemaChangeRead = (SchemaChangeRead) o;
    return Objects.equals(this.afterJson, schemaChangeRead.afterJson) &&
        equalsNullable(this.approvedAt, schemaChangeRead.approvedAt) &&
        equalsNullable(this.approvedBy, schemaChangeRead.approvedBy) &&
        Objects.equals(this.beforeJson, schemaChangeRead.beforeJson) &&
        Objects.equals(this.change, schemaChangeRead.change) &&
        Objects.equals(this.columnName, schemaChangeRead.columnName) &&
        Objects.equals(this.createdAt, schemaChangeRead.createdAt) &&
        Objects.equals(this.id, schemaChangeRead.id) &&
        Objects.equals(this.llmRationale, schemaChangeRead.llmRationale) &&
        Objects.equals(this.nextSnapshotId, schemaChangeRead.nextSnapshotId) &&
        Objects.equals(this.prevSnapshotId, schemaChangeRead.prevSnapshotId) &&
        Objects.equals(this.tableId, schemaChangeRead.tableId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(afterJson, hashCodeNullable(approvedAt), hashCodeNullable(approvedBy), beforeJson, change, columnName, createdAt, id, llmRationale, nextSnapshotId, prevSnapshotId, tableId);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SchemaChangeRead {\n");
    sb.append("    afterJson: ").append(toIndentedString(afterJson)).append("\n");
    sb.append("    approvedAt: ").append(toIndentedString(approvedAt)).append("\n");
    sb.append("    approvedBy: ").append(toIndentedString(approvedBy)).append("\n");
    sb.append("    beforeJson: ").append(toIndentedString(beforeJson)).append("\n");
    sb.append("    change: ").append(toIndentedString(change)).append("\n");
    sb.append("    columnName: ").append(toIndentedString(columnName)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    llmRationale: ").append(toIndentedString(llmRationale)).append("\n");
    sb.append("    nextSnapshotId: ").append(toIndentedString(nextSnapshotId)).append("\n");
    sb.append("    prevSnapshotId: ").append(toIndentedString(prevSnapshotId)).append("\n");
    sb.append("    tableId: ").append(toIndentedString(tableId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

