/*
 * flyquery
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 26.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firefly.flyquery.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Payload for creating a new semantic dimension.
 */
@JsonPropertyOrder({
  SemanticDimensionCreate.JSON_PROPERTY_DATASET_ID,
  SemanticDimensionCreate.JSON_PROPERTY_DEFINITION_YAML,
  SemanticDimensionCreate.JSON_PROPERTY_DESCRIPTION,
  SemanticDimensionCreate.JSON_PROPERTY_LABEL,
  SemanticDimensionCreate.JSON_PROPERTY_METRIC_TYPE,
  SemanticDimensionCreate.JSON_PROPERTY_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-23T20:01:27.049906+02:00[Europe/Madrid]", comments = "Generator version: 7.22.0")
public class SemanticDimensionCreate {
  public static final String JSON_PROPERTY_DATASET_ID = "dataset_id";
  @javax.annotation.Nonnull
  private UUID datasetId;

  public static final String JSON_PROPERTY_DEFINITION_YAML = "definition_yaml";
  @javax.annotation.Nonnull
  private String definitionYaml;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private JsonNullable<String> description = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LABEL = "label";
  @javax.annotation.Nullable
  private JsonNullable<String> label = JsonNullable.<String>undefined();

  /**
   * Gets or Sets metricType
   */
  public enum MetricTypeEnum {
    SIMPLE(String.valueOf("SIMPLE")),
    
    RATIO(String.valueOf("RATIO")),
    
    DERIVED(String.valueOf("DERIVED")),
    
    CUMULATIVE(String.valueOf("CUMULATIVE"));

    private String value;

    MetricTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MetricTypeEnum fromValue(String value) {
      for (MetricTypeEnum b : MetricTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_METRIC_TYPE = "metric_type";
  @javax.annotation.Nullable
  private MetricTypeEnum metricType = MetricTypeEnum.SIMPLE;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public SemanticDimensionCreate() {
  }

  public SemanticDimensionCreate datasetId(@javax.annotation.Nonnull UUID datasetId) {
    
    this.datasetId = datasetId;
    return this;
  }

  /**
   * Get datasetId
   * @return datasetId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DATASET_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getDatasetId() {
    return datasetId;
  }


  @JsonProperty(value = JSON_PROPERTY_DATASET_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDatasetId(@javax.annotation.Nonnull UUID datasetId) {
    this.datasetId = datasetId;
  }

  public SemanticDimensionCreate definitionYaml(@javax.annotation.Nonnull String definitionYaml) {
    
    this.definitionYaml = definitionYaml;
    return this;
  }

  /**
   * Get definitionYaml
   * @return definitionYaml
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DEFINITION_YAML, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDefinitionYaml() {
    return definitionYaml;
  }


  @JsonProperty(value = JSON_PROPERTY_DEFINITION_YAML, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDefinitionYaml(@javax.annotation.Nonnull String definitionYaml) {
    this.definitionYaml = definitionYaml;
  }

  public SemanticDimensionCreate description(@javax.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }

  public SemanticDimensionCreate label(@javax.annotation.Nullable String label) {
    this.label = JsonNullable.<String>of(label);
    
    return this;
  }

  /**
   * Get label
   * @return label
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getLabel() {
        return label.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LABEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLabel_JsonNullable() {
    return label;
  }
  
  @JsonProperty(JSON_PROPERTY_LABEL)
  public void setLabel_JsonNullable(JsonNullable<String> label) {
    this.label = label;
  }

  public void setLabel(@javax.annotation.Nullable String label) {
    this.label = JsonNullable.<String>of(label);
  }

  public SemanticDimensionCreate metricType(@javax.annotation.Nullable MetricTypeEnum metricType) {
    
    this.metricType = metricType;
    return this;
  }

  /**
   * Get metricType
   * @return metricType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METRIC_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MetricTypeEnum getMetricType() {
    return metricType;
  }


  @JsonProperty(value = JSON_PROPERTY_METRIC_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetricType(@javax.annotation.Nullable MetricTypeEnum metricType) {
    this.metricType = metricType;
  }

  public SemanticDimensionCreate name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SemanticDimensionCreate semanticDimensionCreate = (SemanticDimensionCreate) o;
    return Objects.equals(this.datasetId, semanticDimensionCreate.datasetId) &&
        Objects.equals(this.definitionYaml, semanticDimensionCreate.definitionYaml) &&
        equalsNullable(this.description, semanticDimensionCreate.description) &&
        equalsNullable(this.label, semanticDimensionCreate.label) &&
        Objects.equals(this.metricType, semanticDimensionCreate.metricType) &&
        Objects.equals(this.name, semanticDimensionCreate.name);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(datasetId, definitionYaml, hashCodeNullable(description), hashCodeNullable(label), metricType, name);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SemanticDimensionCreate {\n");
    sb.append("    datasetId: ").append(toIndentedString(datasetId)).append("\n");
    sb.append("    definitionYaml: ").append(toIndentedString(definitionYaml)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    metricType: ").append(toIndentedString(metricType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

