/*
 * flyquery
 * Operational Structured-Data Intelligence (upload-driven) -- multi-tenant ingestion + Text-to-SQL over user-uploaded structured files (CSV / TSV / XLSX / XLS / ODS / JSON / JSONL / Parquet / Avro / ORC / Arrow / Feather + .gz/.zip/.bz2 variants). Materialises uploads to Parquet on object storage; indexes a long-lived schema knowledge base; answers natural-language questions via a multi-agent pipeline. Part of Firefly OperationOS.
 *
 * The version of the OpenAPI document: 26.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firefly.flyquery.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Response from GET /api/v1/stats -- compact workspace summary.
 */
@JsonPropertyOrder({
  WorkspaceStats.JSON_PROPERTY_DATASET_COUNT,
  WorkspaceStats.JSON_PROPERTY_INGEST_JOB_COUNT_PENDING,
  WorkspaceStats.JSON_PROPERTY_QUERY_COUNT_LAST30D,
  WorkspaceStats.JSON_PROPERTY_STORAGE_USED_BYTES,
  WorkspaceStats.JSON_PROPERTY_TABLE_COUNT,
  WorkspaceStats.JSON_PROPERTY_TOKEN_COUNT_LAST30D
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-24T17:01:34.733622+02:00[Europe/Madrid]", comments = "Generator version: 7.22.0")
public class WorkspaceStats {
  public static final String JSON_PROPERTY_DATASET_COUNT = "dataset_count";
  @jakarta.annotation.Nonnull
  private Integer datasetCount;

  public static final String JSON_PROPERTY_INGEST_JOB_COUNT_PENDING = "ingest_job_count_pending";
  @jakarta.annotation.Nonnull
  private Integer ingestJobCountPending;

  public static final String JSON_PROPERTY_QUERY_COUNT_LAST30D = "query_count_last_30d";
  @jakarta.annotation.Nonnull
  private Integer queryCountLast30d;

  public static final String JSON_PROPERTY_STORAGE_USED_BYTES = "storage_used_bytes";
  @jakarta.annotation.Nonnull
  private Integer storageUsedBytes;

  public static final String JSON_PROPERTY_TABLE_COUNT = "table_count";
  @jakarta.annotation.Nonnull
  private Integer tableCount;

  public static final String JSON_PROPERTY_TOKEN_COUNT_LAST30D = "token_count_last_30d";
  @jakarta.annotation.Nonnull
  private Integer tokenCountLast30d;

  public WorkspaceStats() {
  }

  public WorkspaceStats datasetCount(@jakarta.annotation.Nonnull Integer datasetCount) {
    
    this.datasetCount = datasetCount;
    return this;
  }

  /**
   * Get datasetCount
   * @return datasetCount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DATASET_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getDatasetCount() {
    return datasetCount;
  }


  @JsonProperty(value = JSON_PROPERTY_DATASET_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDatasetCount(@jakarta.annotation.Nonnull Integer datasetCount) {
    this.datasetCount = datasetCount;
  }

  public WorkspaceStats ingestJobCountPending(@jakarta.annotation.Nonnull Integer ingestJobCountPending) {
    
    this.ingestJobCountPending = ingestJobCountPending;
    return this;
  }

  /**
   * Get ingestJobCountPending
   * @return ingestJobCountPending
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INGEST_JOB_COUNT_PENDING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getIngestJobCountPending() {
    return ingestJobCountPending;
  }


  @JsonProperty(value = JSON_PROPERTY_INGEST_JOB_COUNT_PENDING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIngestJobCountPending(@jakarta.annotation.Nonnull Integer ingestJobCountPending) {
    this.ingestJobCountPending = ingestJobCountPending;
  }

  public WorkspaceStats queryCountLast30d(@jakarta.annotation.Nonnull Integer queryCountLast30d) {
    
    this.queryCountLast30d = queryCountLast30d;
    return this;
  }

  /**
   * Get queryCountLast30d
   * @return queryCountLast30d
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_QUERY_COUNT_LAST30D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getQueryCountLast30d() {
    return queryCountLast30d;
  }


  @JsonProperty(value = JSON_PROPERTY_QUERY_COUNT_LAST30D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQueryCountLast30d(@jakarta.annotation.Nonnull Integer queryCountLast30d) {
    this.queryCountLast30d = queryCountLast30d;
  }

  public WorkspaceStats storageUsedBytes(@jakarta.annotation.Nonnull Integer storageUsedBytes) {
    
    this.storageUsedBytes = storageUsedBytes;
    return this;
  }

  /**
   * Get storageUsedBytes
   * @return storageUsedBytes
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STORAGE_USED_BYTES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getStorageUsedBytes() {
    return storageUsedBytes;
  }


  @JsonProperty(value = JSON_PROPERTY_STORAGE_USED_BYTES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStorageUsedBytes(@jakarta.annotation.Nonnull Integer storageUsedBytes) {
    this.storageUsedBytes = storageUsedBytes;
  }

  public WorkspaceStats tableCount(@jakarta.annotation.Nonnull Integer tableCount) {
    
    this.tableCount = tableCount;
    return this;
  }

  /**
   * Get tableCount
   * @return tableCount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TABLE_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTableCount() {
    return tableCount;
  }


  @JsonProperty(value = JSON_PROPERTY_TABLE_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTableCount(@jakarta.annotation.Nonnull Integer tableCount) {
    this.tableCount = tableCount;
  }

  public WorkspaceStats tokenCountLast30d(@jakarta.annotation.Nonnull Integer tokenCountLast30d) {
    
    this.tokenCountLast30d = tokenCountLast30d;
    return this;
  }

  /**
   * Get tokenCountLast30d
   * @return tokenCountLast30d
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOKEN_COUNT_LAST30D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTokenCountLast30d() {
    return tokenCountLast30d;
  }


  @JsonProperty(value = JSON_PROPERTY_TOKEN_COUNT_LAST30D, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTokenCountLast30d(@jakarta.annotation.Nonnull Integer tokenCountLast30d) {
    this.tokenCountLast30d = tokenCountLast30d;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkspaceStats workspaceStats = (WorkspaceStats) o;
    return Objects.equals(this.datasetCount, workspaceStats.datasetCount) &&
        Objects.equals(this.ingestJobCountPending, workspaceStats.ingestJobCountPending) &&
        Objects.equals(this.queryCountLast30d, workspaceStats.queryCountLast30d) &&
        Objects.equals(this.storageUsedBytes, workspaceStats.storageUsedBytes) &&
        Objects.equals(this.tableCount, workspaceStats.tableCount) &&
        Objects.equals(this.tokenCountLast30d, workspaceStats.tokenCountLast30d);
  }

  @Override
  public int hashCode() {
    return Objects.hash(datasetCount, ingestJobCountPending, queryCountLast30d, storageUsedBytes, tableCount, tokenCountLast30d);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkspaceStats {\n");
    sb.append("    datasetCount: ").append(toIndentedString(datasetCount)).append("\n");
    sb.append("    ingestJobCountPending: ").append(toIndentedString(ingestJobCountPending)).append("\n");
    sb.append("    queryCountLast30d: ").append(toIndentedString(queryCountLast30d)).append("\n");
    sb.append("    storageUsedBytes: ").append(toIndentedString(storageUsedBytes)).append("\n");
    sb.append("    tableCount: ").append(toIndentedString(tableCount)).append("\n");
    sb.append("    tokenCountLast30d: ").append(toIndentedString(tokenCountLast30d)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

