/*
 * flyquery
 * Operational Structured-Data Intelligence (upload-driven) -- multi-tenant ingestion + Text-to-SQL over user-uploaded structured files (CSV / TSV / XLSX / XLS / ODS / JSON / JSONL / Parquet / Avro / ORC / Arrow / Feather + .gz/.zip/.bz2 variants). Materialises uploads to Parquet on object storage; indexes a long-lived schema knowledge base; answers natural-language questions via a multi-agent pipeline. Part of Firefly OperationOS.
 *
 * The version of the OpenAPI document: 26.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firefly.flyquery.api;

import com.firefly.flyquery.model.DatasetRead;
import java.util.UUID;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for AgentDatasetsApi
 */
@Disabled
public class AgentDatasetsApiTest {

    private final AgentDatasetsApi api = new AgentDatasetsApi();

    
    /**
     * Search / filter datasets visible to this agent&#39;s tenant.
     *
     * 
     */
    @Test
    public void listDatasetsTest()  {
        // uncomment below to test the function
        //String xAgentToken = null;
        //String q = null;
        //String name = null;
        //String status = null;
        //String workspaceId = null;
        //Integer limit = null;
        //Integer offset = null;
        //UUID xCorrelationId = null;
        //api.listDatasets(xAgentToken, q, name, status, workspaceId, limit, offset, xCorrelationId).block();

        // TODO: test validations
    }
    
    /**
     * Fetch a single dataset by id.
     *
     * 
     */
    @Test
    public void readTest()  {
        // uncomment below to test the function
        //String datasetId = null;
        //String xAgentToken = null;
        //UUID xCorrelationId = null;
        //DatasetRead response = api.read(datasetId, xAgentToken, xCorrelationId).block();

        // TODO: test validations
    }
    
    /**
     * Resolve a dataset by &#x60;&#x60;(tenant, workspace, name)&#x60;&#x60;.
     *
     * 
     */
    @Test
    public void readByNameTest()  {
        // uncomment below to test the function
        //String name = null;
        //String xAgentToken = null;
        //UUID xCorrelationId = null;
        //DatasetRead response = api.readByName(name, xAgentToken, xCorrelationId).block();

        // TODO: test validations
    }
    
}
