/*
 * flyquery
 * Operational Structured-Data Intelligence (upload-driven) -- multi-tenant ingestion + Text-to-SQL over user-uploaded structured files (CSV / TSV / XLSX / XLS / ODS / JSON / JSONL / Parquet / Avro / ORC / Arrow / Feather + .gz/.zip/.bz2 variants). Materialises uploads to Parquet on object storage; indexes a long-lived schema knowledge base; answers natural-language questions via a multi-agent pipeline. Part of Firefly OperationOS.
 *
 * The version of the OpenAPI document: 26.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firefly.flyquery.api;

import com.firefly.flyquery.model.PaginatedCostEventRead;
import java.util.UUID;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for CostEventsApi
 */
@Disabled
public class CostEventsApiTest {

    private final CostEventsApi api = new CostEventsApi();

    
    /**
     * List cost events for the caller&#39;s workspace, newest first.
     *
     * Filters ------- * &#x60;&#x60;actor&#x60;&#x60;     -- exact match * &#x60;&#x60;model&#x60;&#x60;     -- exact match (&#x60;&#x60;anthropic:claude-sonnet-4-6&#x60;&#x60; etc.) * &#x60;&#x60;operation&#x60;&#x60; -- exact match (&#x60;&#x60;grounding&#x60;&#x60; / &#x60;&#x60;generation&#x60;&#x60; / ...) * &#x60;&#x60;date_from&#x60;&#x60; -- inclusive lower bound on &#x60;&#x60;created_at&#x60;&#x60; * &#x60;&#x60;date_to&#x60;&#x60;   -- exclusive upper bound on &#x60;&#x60;created_at&#x60;&#x60;
     */
    @Test
    public void listEventsTest()  {
        // uncomment below to test the function
        //String xTenantId = null;
        //String xWorkspaceId = null;
        //String actor = null;
        //String model = null;
        //String operation = null;
        //String dateFrom = null;
        //String dateTo = null;
        //Integer limit = null;
        //Integer offset = null;
        //UUID xCorrelationId = null;
        //PaginatedCostEventRead response = api.listEvents(xTenantId, xWorkspaceId, actor, model, operation, dateFrom, dateTo, limit, offset, xCorrelationId).block();

        // TODO: test validations
    }
    
}
