/*
 * flyquery
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 26.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firefly.flyquery.api;

import com.firefly.flyquery.model.HTTPValidationError;
import com.firefly.flyquery.model.SemanticDimensionCreate;
import com.firefly.flyquery.model.SemanticDimensionRead;
import com.firefly.flyquery.model.SemanticDimensionUpdate;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for SemanticDimensionsApi
 */
@Disabled
public class SemanticDimensionsApiTest {

    private final SemanticDimensionsApi api = new SemanticDimensionsApi();

    
    /**
     * Create a new semantic dimension in DRAFT status.
     *
     * 
     */
    @Test
    public void createTest()  {
        // uncomment below to test the function
        //SemanticDimensionCreate semanticDimensionCreate = null;
        //SemanticDimensionRead response = api.create(semanticDimensionCreate).block();

        // TODO: test validations
    }
    
    /**
     * Fetch a single semantic dimension by id.
     *
     * 
     */
    @Test
    public void getDimensionTest()  {
        // uncomment below to test the function
        //String dimensionId = null;
        //SemanticDimensionRead response = api.getDimension(dimensionId).block();

        // TODO: test validations
    }
    
    /**
     * Return version history for a dimension, oldest first.
     *
     * 
     */
    @Test
    public void historyTest()  {
        // uncomment below to test the function
        //String dimensionId = null;
        //api.history(dimensionId).block();

        // TODO: test validations
    }
    
    /**
     * List all semantic dimensions for the caller&#39;s workspace.
     *
     * 
     */
    @Test
    public void listDimensionsTest()  {
        // uncomment below to test the function
        //String datasetId = null;
        //api.listDimensions(datasetId).block();

        // TODO: test validations
    }
    
    /**
     * Validate, compile, and publish a dimension (status → PUBLISHED).
     *
     * 
     */
    @Test
    public void publishTest()  {
        // uncomment below to test the function
        //String dimensionId = null;
        //SemanticDimensionRead response = api.publish(dimensionId).block();

        // TODO: test validations
    }
    
    /**
     * Retire a dimension (status → RETIRED).
     *
     * 
     */
    @Test
    public void retireTest()  {
        // uncomment below to test the function
        //String dimensionId = null;
        //SemanticDimensionRead response = api.retire(dimensionId).block();

        // TODO: test validations
    }
    
    /**
     * Sparse-update a dimension; re-validates YAML if definition changes.
     *
     * 
     */
    @Test
    public void updateTest()  {
        // uncomment below to test the function
        //String dimensionId = null;
        //SemanticDimensionUpdate semanticDimensionUpdate = null;
        //SemanticDimensionRead response = api.update(dimensionId, semanticDimensionUpdate).block();

        // TODO: test validations
    }
    
}
