/*
 * flyquery
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 26.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firefly.flyquery.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DatasetUpdate
 */
class DatasetUpdateTest {
    private final DatasetUpdate model = new DatasetUpdate();

    /**
     * Model tests for DatasetUpdate
     */
    @Test
    void testDatasetUpdate() {
        // TODO: test DatasetUpdate
    }

    /**
     * Test the property 'defaultLocale'
     */
    @Test
    void defaultLocaleTest() {
        // TODO: test defaultLocale
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'driftPolicy'
     */
    @Test
    void driftPolicyTest() {
        // TODO: test driftPolicy
    }

    /**
     * Test the property 'ingestPolicyJson'
     */
    @Test
    void ingestPolicyJsonTest() {
        // TODO: test ingestPolicyJson
    }

    /**
     * Test the property 'metadataJson'
     */
    @Test
    void metadataJsonTest() {
        // TODO: test metadataJson
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

}
