/*
 * flyquery
 * Operational Structured-Data Intelligence (upload-driven) -- multi-tenant ingestion + Text-to-SQL over user-uploaded structured files (CSV / TSV / XLSX / XLS / ODS / JSON / JSONL / Parquet / Avro / ORC / Arrow / Feather + .gz/.zip/.bz2 variants). Materialises uploads to Parquet on object storage; indexes a long-lived schema knowledge base; answers natural-language questions via a multi-agent pipeline. Part of Firefly OperationOS.
 *
 * The version of the OpenAPI document: 26.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firefly.flyquery.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ExampleRead
 */
class ExampleReadTest {
    private final ExampleRead model = new ExampleRead();

    /**
     * Model tests for ExampleRead
     */
    @Test
    void testExampleRead() {
        // TODO: test ExampleRead
    }

    /**
     * Test the property 'citationsJson'
     */
    @Test
    void citationsJsonTest() {
        // TODO: test citationsJson
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'datasetId'
     */
    @Test
    void datasetIdTest() {
        // TODO: test datasetId
    }

    /**
     * Test the property 'generatedSql'
     */
    @Test
    void generatedSqlTest() {
        // TODO: test generatedSql
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'lastUsedAt'
     */
    @Test
    void lastUsedAtTest() {
        // TODO: test lastUsedAt
    }

    /**
     * Test the property 'normalisedSql'
     */
    @Test
    void normalisedSqlTest() {
        // TODO: test normalisedSql
    }

    /**
     * Test the property 'quality'
     */
    @Test
    void qualityTest() {
        // TODO: test quality
    }

    /**
     * Test the property 'question'
     */
    @Test
    void questionTest() {
        // TODO: test question
    }

    /**
     * Test the property 'source'
     */
    @Test
    void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'usageCount'
     */
    @Test
    void usageCountTest() {
        // TODO: test usageCount
    }

    /**
     * Test the property 'workspaceId'
     */
    @Test
    void workspaceIdTest() {
        // TODO: test workspaceId
    }

}
