/*
 * flyquery
 * Operational Structured-Data Intelligence (upload-driven) -- multi-tenant ingestion + Text-to-SQL over user-uploaded structured files (CSV / TSV / XLSX / XLS / ODS / JSON / JSONL / Parquet / Avro / ORC / Arrow / Feather + .gz/.zip/.bz2 variants). Materialises uploads to Parquet on object storage; indexes a long-lived schema knowledge base; answers natural-language questions via a multi-agent pipeline. Part of Firefly OperationOS.
 *
 * The version of the OpenAPI document: 26.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firefly.flyquery.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for QueryResultRead
 */
class QueryResultReadTest {
    private final QueryResultRead model = new QueryResultRead();

    /**
     * Model tests for QueryResultRead
     */
    @Test
    void testQueryResultRead() {
        // TODO: test QueryResultRead
    }

    /**
     * Test the property 'parquetPresignedUrl'
     */
    @Test
    void parquetPresignedUrlTest() {
        // TODO: test parquetPresignedUrl
    }

    /**
     * Test the property 'previewJson'
     */
    @Test
    void previewJsonTest() {
        // TODO: test previewJson
    }

    /**
     * Test the property 'queryId'
     */
    @Test
    void queryIdTest() {
        // TODO: test queryId
    }

    /**
     * Test the property 'resultByteSize'
     */
    @Test
    void resultByteSizeTest() {
        // TODO: test resultByteSize
    }

    /**
     * Test the property 'ttlExpiresAt'
     */
    @Test
    void ttlExpiresAtTest() {
        // TODO: test ttlExpiresAt
    }

}
