/*
 * flyquery
 * Operational Structured-Data Intelligence (upload-driven) -- multi-tenant ingestion + Text-to-SQL over user-uploaded structured files (CSV / TSV / XLSX / XLS / ODS / JSON / JSONL / Parquet / Avro / ORC / Arrow / Feather + .gz/.zip/.bz2 variants). Materialises uploads to Parquet on object storage; indexes a long-lived schema knowledge base; answers natural-language questions via a multi-agent pipeline. Part of Firefly OperationOS.
 *
 * The version of the OpenAPI document: 26.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firefly.flyquery.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.firefly.flyquery.model.Confidence;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RelationRead
 */
class RelationReadTest {
    private final RelationRead model = new RelationRead();

    /**
     * Model tests for RelationRead
     */
    @Test
    void testRelationRead() {
        // TODO: test RelationRead
    }

    /**
     * Test the property 'approvedBy'
     */
    @Test
    void approvedByTest() {
        // TODO: test approvedBy
    }

    /**
     * Test the property 'confidence'
     */
    @Test
    void confidenceTest() {
        // TODO: test confidence
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'datasetId'
     */
    @Test
    void datasetIdTest() {
        // TODO: test datasetId
    }

    /**
     * Test the property 'fromColumnName'
     */
    @Test
    void fromColumnNameTest() {
        // TODO: test fromColumnName
    }

    /**
     * Test the property 'fromTableId'
     */
    @Test
    void fromTableIdTest() {
        // TODO: test fromTableId
    }

    /**
     * Test the property 'fromTableName'
     */
    @Test
    void fromTableNameTest() {
        // TODO: test fromTableName
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'kind'
     */
    @Test
    void kindTest() {
        // TODO: test kind
    }

    /**
     * Test the property 'reason'
     */
    @Test
    void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'toColumnName'
     */
    @Test
    void toColumnNameTest() {
        // TODO: test toColumnName
    }

    /**
     * Test the property 'toTableId'
     */
    @Test
    void toTableIdTest() {
        // TODO: test toTableId
    }

    /**
     * Test the property 'toTableName'
     */
    @Test
    void toTableNameTest() {
        // TODO: test toTableName
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    void updatedAtTest() {
        // TODO: test updatedAt
    }

}
