/*
 * flyquery
 * Operational Structured-Data Intelligence (upload-driven) -- multi-tenant ingestion + Text-to-SQL over user-uploaded structured files (CSV / TSV / XLSX / XLS / ODS / JSON / JSONL / Parquet / Avro / ORC / Arrow / Feather + .gz/.zip/.bz2 variants). Materialises uploads to Parquet on object storage; indexes a long-lived schema knowledge base; answers natural-language questions via a multi-agent pipeline. Part of Firefly OperationOS.
 *
 * The version of the OpenAPI document: 26.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firefly.flyquery.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SnapshotRead
 */
class SnapshotReadTest {
    private final SnapshotRead model = new SnapshotRead();

    /**
     * Model tests for SnapshotRead
     */
    @Test
    void testSnapshotRead() {
        // TODO: test SnapshotRead
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'nColumns'
     */
    @Test
    void nColumnsTest() {
        // TODO: test nColumns
    }

    /**
     * Test the property 'nRowsActual'
     */
    @Test
    void nRowsActualTest() {
        // TODO: test nRowsActual
    }

    /**
     * Test the property 'nRowsEstimate'
     */
    @Test
    void nRowsEstimateTest() {
        // TODO: test nRowsEstimate
    }

    /**
     * Test the property 'parquetByteSize'
     */
    @Test
    void parquetByteSizeTest() {
        // TODO: test parquetByteSize
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'tableId'
     */
    @Test
    void tableIdTest() {
        // TODO: test tableId
    }

    /**
     * Test the property 'takenAt'
     */
    @Test
    void takenAtTest() {
        // TODO: test takenAt
    }

    /**
     * Test the property 'triggeredBy'
     */
    @Test
    void triggeredByTest() {
        // TODO: test triggeredBy
    }

}
