// Copyright 2024-2026 Firefly Software Foundation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * flyquery
 * Operational Structured-Data Intelligence (upload-driven) -- multi-tenant ingestion + Text-to-SQL over user-uploaded structured files (CSV / TSV / XLSX / XLS / ODS / JSON / JSONL / Parquet / Avro / ORC / Arrow / Feather + .gz/.zip/.bz2 variants). Materialises uploads to Parquet on object storage; indexes a long-lived schema knowledge base; answers natural-language questions via a multi-agent pipeline. Part of Firefly OperationOS.
 *
 * The version of the OpenAPI document: 26.5.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firefly.flyquery.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.firefly.flyquery.model.AgentUsage;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UsageSummary
 */
class UsageSummaryTest {
    private final UsageSummary model = new UsageSummary();

    /**
     * Model tests for UsageSummary
     */
    @Test
    void testUsageSummary() {
        // TODO: test UsageSummary
    }

    /**
     * Test the property 'byAgent'
     */
    @Test
    void byAgentTest() {
        // TODO: test byAgent
    }

    /**
     * Test the property 'totalCostUsd'
     */
    @Test
    void totalCostUsdTest() {
        // TODO: test totalCostUsd
    }

    /**
     * Test the property 'totalInputTokens'
     */
    @Test
    void totalInputTokensTest() {
        // TODO: test totalInputTokens
    }

    /**
     * Test the property 'totalLatencyMs'
     */
    @Test
    void totalLatencyMsTest() {
        // TODO: test totalLatencyMs
    }

    /**
     * Test the property 'totalOutputTokens'
     */
    @Test
    void totalOutputTokensTest() {
        // TODO: test totalOutputTokens
    }

    /**
     * Test the property 'totalTokens'
     */
    @Test
    void totalTokensTest() {
        // TODO: test totalTokens
    }

}
