/*
 * flyquery
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 26.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.firefly.flyquery.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.firefly.flyquery.model.ClarificationFrame;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AnswerResponse
 */
public class AnswerResponseTest {
    private final AnswerResponse model = new AnswerResponse();

    /**
     * Model tests for AnswerResponse
     */
    @Test
    public void testAnswerResponse() {
        // TODO: test AnswerResponse
    }

    /**
     * Test the property 'chartHint'
     */
    @Test
    public void chartHintTest() {
        // TODO: test chartHint
    }

    /**
     * Test the property 'clarification'
     */
    @Test
    public void clarificationTest() {
        // TODO: test clarification
    }

    /**
     * Test the property 'elapsedMs'
     */
    @Test
    public void elapsedMsTest() {
        // TODO: test elapsedMs
    }

    /**
     * Test the property 'executionStatus'
     */
    @Test
    public void executionStatusTest() {
        // TODO: test executionStatus
    }

    /**
     * Test the property 'explanation'
     */
    @Test
    public void explanationTest() {
        // TODO: test explanation
    }

    /**
     * Test the property 'groundedSummary'
     */
    @Test
    public void groundedSummaryTest() {
        // TODO: test groundedSummary
    }

    /**
     * Test the property 'preview'
     */
    @Test
    public void previewTest() {
        // TODO: test preview
    }

    /**
     * Test the property 'queryId'
     */
    @Test
    public void queryIdTest() {
        // TODO: test queryId
    }

    /**
     * Test the property 'rowCount'
     */
    @Test
    public void rowCountTest() {
        // TODO: test rowCount
    }

    /**
     * Test the property 'snapshotPins'
     */
    @Test
    public void snapshotPinsTest() {
        // TODO: test snapshotPins
    }

    /**
     * Test the property 'sql'
     */
    @Test
    public void sqlTest() {
        // TODO: test sql
    }

    /**
     * Test the property 'truncated'
     */
    @Test
    public void truncatedTest() {
        // TODO: test truncated
    }

}
