/*
 * flyquery
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 26.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.firefly.flyquery.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ClarificationFrame
 */
public class ClarificationFrameTest {
    private final ClarificationFrame model = new ClarificationFrame();

    /**
     * Model tests for ClarificationFrame
     */
    @Test
    public void testClarificationFrame() {
        // TODO: test ClarificationFrame
    }

    /**
     * Test the property 'questions'
     */
    @Test
    public void questionsTest() {
        // TODO: test questions
    }

    /**
     * Test the property 'reasons'
     */
    @Test
    public void reasonsTest() {
        // TODO: test reasons
    }

}
