/*
 * flyquery
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 26.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.firefly.flyquery.model;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LocationInner
 */
public class LocationInnerTest {
    private final LocationInner model = new LocationInner();

    /**
     * Model tests for LocationInner
     */
    @Test
    public void testLocationInner() {
        // TODO: test LocationInner
    }

}
