/*
 * flyquery
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 26.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.firefly.flyquery.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SchemaObjectRead
 */
public class SchemaObjectReadTest {
    private final SchemaObjectRead model = new SchemaObjectRead();

    /**
     * Model tests for SchemaObjectRead
     */
    @Test
    public void testSchemaObjectRead() {
        // TODO: test SchemaObjectRead
    }

    /**
     * Test the property 'businessOwner'
     */
    @Test
    public void businessOwnerTest() {
        // TODO: test businessOwner
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'dataType'
     */
    @Test
    public void dataTypeTest() {
        // TODO: test dataType
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'descriptionSource'
     */
    @Test
    public void descriptionSourceTest() {
        // TODO: test descriptionSource
    }

    /**
     * Test the property 'governanceJson'
     */
    @Test
    public void governanceJsonTest() {
        // TODO: test governanceJson
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    public void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'isNullable'
     */
    @Test
    public void isNullableTest() {
        // TODO: test isNullable
    }

    /**
     * Test the property 'kind'
     */
    @Test
    public void kindTest() {
        // TODO: test kind
    }

    /**
     * Test the property 'lastChangedAt'
     */
    @Test
    public void lastChangedAtTest() {
        // TODO: test lastChangedAt
    }

    /**
     * Test the property 'piiSource'
     */
    @Test
    public void piiSourceTest() {
        // TODO: test piiSource
    }

    /**
     * Test the property 'piiTag'
     */
    @Test
    public void piiTagTest() {
        // TODO: test piiTag
    }

    /**
     * Test the property 'qualifiedName'
     */
    @Test
    public void qualifiedNameTest() {
        // TODO: test qualifiedName
    }

    /**
     * Test the property 'snapshotId'
     */
    @Test
    public void snapshotIdTest() {
        // TODO: test snapshotId
    }

    /**
     * Test the property 'synonymsJson'
     */
    @Test
    public void synonymsJsonTest() {
        // TODO: test synonymsJson
    }

    /**
     * Test the property 'tableId'
     */
    @Test
    public void tableIdTest() {
        // TODO: test tableId
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'workspaceId'
     */
    @Test
    public void workspaceIdTest() {
        // TODO: test workspaceId
    }

}
