/*
 * flyquery
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 26.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.firefly.flyquery.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TurnRead
 */
public class TurnReadTest {
    private final TurnRead model = new TurnRead();

    /**
     * Model tests for TurnRead
     */
    @Test
    public void testTurnRead() {
        // TODO: test TurnRead
    }

    /**
     * Test the property 'conversationId'
     */
    @Test
    public void conversationIdTest() {
        // TODO: test conversationId
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'elapsedMs'
     */
    @Test
    public void elapsedMsTest() {
        // TODO: test elapsedMs
    }

    /**
     * Test the property 'executedSql'
     */
    @Test
    public void executedSqlTest() {
        // TODO: test executedSql
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'noAnswer'
     */
    @Test
    public void noAnswerTest() {
        // TODO: test noAnswer
    }

    /**
     * Test the property 'question'
     */
    @Test
    public void questionTest() {
        // TODO: test question
    }

    /**
     * Test the property 'snapshotPinsJson'
     */
    @Test
    public void snapshotPinsJsonTest() {
        // TODO: test snapshotPinsJson
    }

    /**
     * Test the property 'summary'
     */
    @Test
    public void summaryTest() {
        // TODO: test summary
    }

    /**
     * Test the property 'tableQnamesJson'
     */
    @Test
    public void tableQnamesJsonTest() {
        // TODO: test tableQnamesJson
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'turnIndex'
     */
    @Test
    public void turnIndexTest() {
        // TODO: test turnIndex
    }

    /**
     * Test the property 'workspaceId'
     */
    @Test
    public void workspaceIdTest() {
        // TODO: test workspaceId
    }

}
