/*
 * flyquery
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 26.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.firefly.flyquery.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.firefly.flyquery.JSON;

/**
 * Mint response: includes the full &#x60;&#x60;token&#x60;&#x60; ONCE.  Subsequent reads only ever expose &#x60;&#x60;prefix&#x60;&#x60; -- the secret hash is stored server-side and never returned. Callers MUST capture the token at mint time; there is no recovery path.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-23T19:16:18.581048+02:00[Europe/Madrid]", comments = "Generator version: 7.22.0")
public class AgentTokenCreated {
  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_CREATED_BY = "created_by";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  @javax.annotation.Nonnull
  private String createdBy;

  public static final String SERIALIZED_NAME_EXPIRES_AT = "expires_at";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AT)
  @javax.annotation.Nullable
  private OffsetDateTime expiresAt;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_LAST_USED_AT = "last_used_at";
  @SerializedName(SERIALIZED_NAME_LAST_USED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime lastUsedAt;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_PREFIX = "prefix";
  @SerializedName(SERIALIZED_NAME_PREFIX)
  @javax.annotation.Nonnull
  private String prefix;

  public static final String SERIALIZED_NAME_RATE_LIMIT_RPM = "rate_limit_rpm";
  @SerializedName(SERIALIZED_NAME_RATE_LIMIT_RPM)
  @javax.annotation.Nullable
  private Integer rateLimitRpm;

  public static final String SERIALIZED_NAME_REVOKED_AT = "revoked_at";
  @SerializedName(SERIALIZED_NAME_REVOKED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime revokedAt;

  public static final String SERIALIZED_NAME_SCOPES = "scopes";
  @SerializedName(SERIALIZED_NAME_SCOPES)
  @javax.annotation.Nonnull
  private List<String> scopes = new ArrayList<>();

  public static final String SERIALIZED_NAME_TOKEN = "token";
  @SerializedName(SERIALIZED_NAME_TOKEN)
  @javax.annotation.Nonnull
  private String token;

  public static final String SERIALIZED_NAME_WORKSPACE_ALLOWLIST = "workspace_allowlist";
  @SerializedName(SERIALIZED_NAME_WORKSPACE_ALLOWLIST)
  @javax.annotation.Nullable
  private List<String> workspaceAllowlist;

  public AgentTokenCreated() {
  }

  public AgentTokenCreated createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public AgentTokenCreated createdBy(@javax.annotation.Nonnull String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

  /**
   * Get createdBy
   * @return createdBy
   */
  @javax.annotation.Nonnull
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(@javax.annotation.Nonnull String createdBy) {
    this.createdBy = createdBy;
  }


  public AgentTokenCreated expiresAt(@javax.annotation.Nullable OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(@javax.annotation.Nullable OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }


  public AgentTokenCreated id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public AgentTokenCreated lastUsedAt(@javax.annotation.Nullable OffsetDateTime lastUsedAt) {
    this.lastUsedAt = lastUsedAt;
    return this;
  }

  /**
   * Get lastUsedAt
   * @return lastUsedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getLastUsedAt() {
    return lastUsedAt;
  }

  public void setLastUsedAt(@javax.annotation.Nullable OffsetDateTime lastUsedAt) {
    this.lastUsedAt = lastUsedAt;
  }


  public AgentTokenCreated name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public AgentTokenCreated prefix(@javax.annotation.Nonnull String prefix) {
    this.prefix = prefix;
    return this;
  }

  /**
   * Get prefix
   * @return prefix
   */
  @javax.annotation.Nonnull
  public String getPrefix() {
    return prefix;
  }

  public void setPrefix(@javax.annotation.Nonnull String prefix) {
    this.prefix = prefix;
  }


  public AgentTokenCreated rateLimitRpm(@javax.annotation.Nullable Integer rateLimitRpm) {
    this.rateLimitRpm = rateLimitRpm;
    return this;
  }

  /**
   * Get rateLimitRpm
   * @return rateLimitRpm
   */
  @javax.annotation.Nullable
  public Integer getRateLimitRpm() {
    return rateLimitRpm;
  }

  public void setRateLimitRpm(@javax.annotation.Nullable Integer rateLimitRpm) {
    this.rateLimitRpm = rateLimitRpm;
  }


  public AgentTokenCreated revokedAt(@javax.annotation.Nullable OffsetDateTime revokedAt) {
    this.revokedAt = revokedAt;
    return this;
  }

  /**
   * Get revokedAt
   * @return revokedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getRevokedAt() {
    return revokedAt;
  }

  public void setRevokedAt(@javax.annotation.Nullable OffsetDateTime revokedAt) {
    this.revokedAt = revokedAt;
  }


  public AgentTokenCreated scopes(@javax.annotation.Nonnull List<String> scopes) {
    this.scopes = scopes;
    return this;
  }

  public AgentTokenCreated addScopesItem(String scopesItem) {
    if (this.scopes == null) {
      this.scopes = new ArrayList<>();
    }
    this.scopes.add(scopesItem);
    return this;
  }

  /**
   * Get scopes
   * @return scopes
   */
  @javax.annotation.Nonnull
  public List<String> getScopes() {
    return scopes;
  }

  public void setScopes(@javax.annotation.Nonnull List<String> scopes) {
    this.scopes = scopes;
  }


  public AgentTokenCreated token(@javax.annotation.Nonnull String token) {
    this.token = token;
    return this;
  }

  /**
   * Get token
   * @return token
   */
  @javax.annotation.Nonnull
  public String getToken() {
    return token;
  }

  public void setToken(@javax.annotation.Nonnull String token) {
    this.token = token;
  }


  public AgentTokenCreated workspaceAllowlist(@javax.annotation.Nullable List<String> workspaceAllowlist) {
    this.workspaceAllowlist = workspaceAllowlist;
    return this;
  }

  public AgentTokenCreated addWorkspaceAllowlistItem(String workspaceAllowlistItem) {
    if (this.workspaceAllowlist == null) {
      this.workspaceAllowlist = new ArrayList<>();
    }
    this.workspaceAllowlist.add(workspaceAllowlistItem);
    return this;
  }

  /**
   * Get workspaceAllowlist
   * @return workspaceAllowlist
   */
  @javax.annotation.Nullable
  public List<String> getWorkspaceAllowlist() {
    return workspaceAllowlist;
  }

  public void setWorkspaceAllowlist(@javax.annotation.Nullable List<String> workspaceAllowlist) {
    this.workspaceAllowlist = workspaceAllowlist;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgentTokenCreated agentTokenCreated = (AgentTokenCreated) o;
    return Objects.equals(this.createdAt, agentTokenCreated.createdAt) &&
        Objects.equals(this.createdBy, agentTokenCreated.createdBy) &&
        Objects.equals(this.expiresAt, agentTokenCreated.expiresAt) &&
        Objects.equals(this.id, agentTokenCreated.id) &&
        Objects.equals(this.lastUsedAt, agentTokenCreated.lastUsedAt) &&
        Objects.equals(this.name, agentTokenCreated.name) &&
        Objects.equals(this.prefix, agentTokenCreated.prefix) &&
        Objects.equals(this.rateLimitRpm, agentTokenCreated.rateLimitRpm) &&
        Objects.equals(this.revokedAt, agentTokenCreated.revokedAt) &&
        Objects.equals(this.scopes, agentTokenCreated.scopes) &&
        Objects.equals(this.token, agentTokenCreated.token) &&
        Objects.equals(this.workspaceAllowlist, agentTokenCreated.workspaceAllowlist);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, createdBy, expiresAt, id, lastUsedAt, name, prefix, rateLimitRpm, revokedAt, scopes, token, workspaceAllowlist);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgentTokenCreated {\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastUsedAt: ").append(toIndentedString(lastUsedAt)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    rateLimitRpm: ").append(toIndentedString(rateLimitRpm)).append("\n");
    sb.append("    revokedAt: ").append(toIndentedString(revokedAt)).append("\n");
    sb.append("    scopes: ").append(toIndentedString(scopes)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    workspaceAllowlist: ").append(toIndentedString(workspaceAllowlist)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("created_at", "created_by", "expires_at", "id", "last_used_at", "name", "prefix", "rate_limit_rpm", "revoked_at", "scopes", "token", "workspace_allowlist"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("created_at", "created_by", "expires_at", "id", "last_used_at", "name", "prefix", "rate_limit_rpm", "revoked_at", "scopes", "token", "workspace_allowlist"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AgentTokenCreated
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AgentTokenCreated.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AgentTokenCreated is not found in the empty JSON string", AgentTokenCreated.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AgentTokenCreated.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `AgentTokenCreated` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AgentTokenCreated.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("created_by").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `created_by` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created_by").toString()));
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("prefix").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `prefix` to be a primitive type in the JSON string but got `%s`", jsonObj.get("prefix").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("scopes") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("scopes").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `scopes` to be an array in the JSON string but got `%s`", jsonObj.get("scopes").toString()));
      }
      if (!jsonObj.get("token").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `token` to be a primitive type in the JSON string but got `%s`", jsonObj.get("token").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("workspace_allowlist") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("workspace_allowlist").isJsonArray() && !jsonObj.get("workspace_allowlist").isJsonNull()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `workspace_allowlist` to be an array in the JSON string but got `%s`", jsonObj.get("workspace_allowlist").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AgentTokenCreated.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AgentTokenCreated' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AgentTokenCreated> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AgentTokenCreated.class));

       return (TypeAdapter<T>) new TypeAdapter<AgentTokenCreated>() {
           @Override
           public void write(JsonWriter out, AgentTokenCreated value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AgentTokenCreated read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AgentTokenCreated given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AgentTokenCreated
   * @throws IOException if the JSON string is invalid with respect to AgentTokenCreated
   */
  public static AgentTokenCreated fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AgentTokenCreated.class);
  }

  /**
   * Convert an instance of AgentTokenCreated to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

