/*
 * flyquery
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 26.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.firefly.flyquery.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.firefly.flyquery.JSON;

/**
 * Full read representation of a flyquery_examples row.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-23T19:16:18.581048+02:00[Europe/Madrid]", comments = "Generator version: 7.22.0")
public class ExampleRead {
  public static final String SERIALIZED_NAME_CITATIONS_JSON = "citations_json";
  @SerializedName(SERIALIZED_NAME_CITATIONS_JSON)
  @javax.annotation.Nonnull
  private Map<String, Object> citationsJson = new HashMap<>();

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_CREATED_BY = "created_by";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  @javax.annotation.Nonnull
  private String createdBy;

  public static final String SERIALIZED_NAME_DATASET_ID = "dataset_id";
  @SerializedName(SERIALIZED_NAME_DATASET_ID)
  @javax.annotation.Nullable
  private UUID datasetId;

  public static final String SERIALIZED_NAME_GENERATED_SQL = "generated_sql";
  @SerializedName(SERIALIZED_NAME_GENERATED_SQL)
  @javax.annotation.Nonnull
  private String generatedSql;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private UUID id;

  public static final String SERIALIZED_NAME_LAST_USED_AT = "last_used_at";
  @SerializedName(SERIALIZED_NAME_LAST_USED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime lastUsedAt;

  public static final String SERIALIZED_NAME_NORMALISED_SQL = "normalised_sql";
  @SerializedName(SERIALIZED_NAME_NORMALISED_SQL)
  @javax.annotation.Nonnull
  private String normalisedSql;

  /**
   * Gets or Sets quality
   */
  @JsonAdapter(QualityEnum.Adapter.class)
  public enum QualityEnum {
    PROPOSED("PROPOSED"),
    
    APPROVED("APPROVED"),
    
    REJECTED("REJECTED");

    private String value;

    QualityEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static QualityEnum fromValue(String value) {
      for (QualityEnum b : QualityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<QualityEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final QualityEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public QualityEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return QualityEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      QualityEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_QUALITY = "quality";
  @SerializedName(SERIALIZED_NAME_QUALITY)
  @javax.annotation.Nonnull
  private QualityEnum quality;

  public static final String SERIALIZED_NAME_QUESTION = "question";
  @SerializedName(SERIALIZED_NAME_QUESTION)
  @javax.annotation.Nonnull
  private String question;

  /**
   * Gets or Sets source
   */
  @JsonAdapter(SourceEnum.Adapter.class)
  public enum SourceEnum {
    USER_CURATED("USER_CURATED"),
    
    AGENT_LEARNED("AGENT_LEARNED");

    private String value;

    SourceEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SourceEnum fromValue(String value) {
      for (SourceEnum b : SourceEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SourceEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SourceEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SourceEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SourceEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      SourceEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_SOURCE = "source";
  @SerializedName(SERIALIZED_NAME_SOURCE)
  @javax.annotation.Nonnull
  private SourceEnum source;

  public static final String SERIALIZED_NAME_TENANT_ID = "tenant_id";
  @SerializedName(SERIALIZED_NAME_TENANT_ID)
  @javax.annotation.Nonnull
  private String tenantId;

  public static final String SERIALIZED_NAME_USAGE_COUNT = "usage_count";
  @SerializedName(SERIALIZED_NAME_USAGE_COUNT)
  @javax.annotation.Nonnull
  private Integer usageCount;

  public static final String SERIALIZED_NAME_WORKSPACE_ID = "workspace_id";
  @SerializedName(SERIALIZED_NAME_WORKSPACE_ID)
  @javax.annotation.Nonnull
  private UUID workspaceId;

  public ExampleRead() {
  }

  public ExampleRead citationsJson(@javax.annotation.Nonnull Map<String, Object> citationsJson) {
    this.citationsJson = citationsJson;
    return this;
  }

  public ExampleRead putCitationsJsonItem(String key, Object citationsJsonItem) {
    if (this.citationsJson == null) {
      this.citationsJson = new HashMap<>();
    }
    this.citationsJson.put(key, citationsJsonItem);
    return this;
  }

  /**
   * Get citationsJson
   * @return citationsJson
   */
  @javax.annotation.Nonnull
  public Map<String, Object> getCitationsJson() {
    return citationsJson;
  }

  public void setCitationsJson(@javax.annotation.Nonnull Map<String, Object> citationsJson) {
    this.citationsJson = citationsJson;
  }


  public ExampleRead createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public ExampleRead createdBy(@javax.annotation.Nonnull String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

  /**
   * Get createdBy
   * @return createdBy
   */
  @javax.annotation.Nonnull
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(@javax.annotation.Nonnull String createdBy) {
    this.createdBy = createdBy;
  }


  public ExampleRead datasetId(@javax.annotation.Nullable UUID datasetId) {
    this.datasetId = datasetId;
    return this;
  }

  /**
   * Get datasetId
   * @return datasetId
   */
  @javax.annotation.Nullable
  public UUID getDatasetId() {
    return datasetId;
  }

  public void setDatasetId(@javax.annotation.Nullable UUID datasetId) {
    this.datasetId = datasetId;
  }


  public ExampleRead generatedSql(@javax.annotation.Nonnull String generatedSql) {
    this.generatedSql = generatedSql;
    return this;
  }

  /**
   * Get generatedSql
   * @return generatedSql
   */
  @javax.annotation.Nonnull
  public String getGeneratedSql() {
    return generatedSql;
  }

  public void setGeneratedSql(@javax.annotation.Nonnull String generatedSql) {
    this.generatedSql = generatedSql;
  }


  public ExampleRead id(@javax.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public UUID getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public ExampleRead lastUsedAt(@javax.annotation.Nullable OffsetDateTime lastUsedAt) {
    this.lastUsedAt = lastUsedAt;
    return this;
  }

  /**
   * Get lastUsedAt
   * @return lastUsedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getLastUsedAt() {
    return lastUsedAt;
  }

  public void setLastUsedAt(@javax.annotation.Nullable OffsetDateTime lastUsedAt) {
    this.lastUsedAt = lastUsedAt;
  }


  public ExampleRead normalisedSql(@javax.annotation.Nonnull String normalisedSql) {
    this.normalisedSql = normalisedSql;
    return this;
  }

  /**
   * Get normalisedSql
   * @return normalisedSql
   */
  @javax.annotation.Nonnull
  public String getNormalisedSql() {
    return normalisedSql;
  }

  public void setNormalisedSql(@javax.annotation.Nonnull String normalisedSql) {
    this.normalisedSql = normalisedSql;
  }


  public ExampleRead quality(@javax.annotation.Nonnull QualityEnum quality) {
    this.quality = quality;
    return this;
  }

  /**
   * Get quality
   * @return quality
   */
  @javax.annotation.Nonnull
  public QualityEnum getQuality() {
    return quality;
  }

  public void setQuality(@javax.annotation.Nonnull QualityEnum quality) {
    this.quality = quality;
  }


  public ExampleRead question(@javax.annotation.Nonnull String question) {
    this.question = question;
    return this;
  }

  /**
   * Get question
   * @return question
   */
  @javax.annotation.Nonnull
  public String getQuestion() {
    return question;
  }

  public void setQuestion(@javax.annotation.Nonnull String question) {
    this.question = question;
  }


  public ExampleRead source(@javax.annotation.Nonnull SourceEnum source) {
    this.source = source;
    return this;
  }

  /**
   * Get source
   * @return source
   */
  @javax.annotation.Nonnull
  public SourceEnum getSource() {
    return source;
  }

  public void setSource(@javax.annotation.Nonnull SourceEnum source) {
    this.source = source;
  }


  public ExampleRead tenantId(@javax.annotation.Nonnull String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

  /**
   * Get tenantId
   * @return tenantId
   */
  @javax.annotation.Nonnull
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(@javax.annotation.Nonnull String tenantId) {
    this.tenantId = tenantId;
  }


  public ExampleRead usageCount(@javax.annotation.Nonnull Integer usageCount) {
    this.usageCount = usageCount;
    return this;
  }

  /**
   * Get usageCount
   * @return usageCount
   */
  @javax.annotation.Nonnull
  public Integer getUsageCount() {
    return usageCount;
  }

  public void setUsageCount(@javax.annotation.Nonnull Integer usageCount) {
    this.usageCount = usageCount;
  }


  public ExampleRead workspaceId(@javax.annotation.Nonnull UUID workspaceId) {
    this.workspaceId = workspaceId;
    return this;
  }

  /**
   * Get workspaceId
   * @return workspaceId
   */
  @javax.annotation.Nonnull
  public UUID getWorkspaceId() {
    return workspaceId;
  }

  public void setWorkspaceId(@javax.annotation.Nonnull UUID workspaceId) {
    this.workspaceId = workspaceId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExampleRead exampleRead = (ExampleRead) o;
    return Objects.equals(this.citationsJson, exampleRead.citationsJson) &&
        Objects.equals(this.createdAt, exampleRead.createdAt) &&
        Objects.equals(this.createdBy, exampleRead.createdBy) &&
        Objects.equals(this.datasetId, exampleRead.datasetId) &&
        Objects.equals(this.generatedSql, exampleRead.generatedSql) &&
        Objects.equals(this.id, exampleRead.id) &&
        Objects.equals(this.lastUsedAt, exampleRead.lastUsedAt) &&
        Objects.equals(this.normalisedSql, exampleRead.normalisedSql) &&
        Objects.equals(this.quality, exampleRead.quality) &&
        Objects.equals(this.question, exampleRead.question) &&
        Objects.equals(this.source, exampleRead.source) &&
        Objects.equals(this.tenantId, exampleRead.tenantId) &&
        Objects.equals(this.usageCount, exampleRead.usageCount) &&
        Objects.equals(this.workspaceId, exampleRead.workspaceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(citationsJson, createdAt, createdBy, datasetId, generatedSql, id, lastUsedAt, normalisedSql, quality, question, source, tenantId, usageCount, workspaceId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExampleRead {\n");
    sb.append("    citationsJson: ").append(toIndentedString(citationsJson)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    datasetId: ").append(toIndentedString(datasetId)).append("\n");
    sb.append("    generatedSql: ").append(toIndentedString(generatedSql)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastUsedAt: ").append(toIndentedString(lastUsedAt)).append("\n");
    sb.append("    normalisedSql: ").append(toIndentedString(normalisedSql)).append("\n");
    sb.append("    quality: ").append(toIndentedString(quality)).append("\n");
    sb.append("    question: ").append(toIndentedString(question)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    usageCount: ").append(toIndentedString(usageCount)).append("\n");
    sb.append("    workspaceId: ").append(toIndentedString(workspaceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("citations_json", "created_at", "created_by", "dataset_id", "generated_sql", "id", "last_used_at", "normalised_sql", "quality", "question", "source", "tenant_id", "usage_count", "workspace_id"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("citations_json", "created_at", "created_by", "dataset_id", "generated_sql", "id", "last_used_at", "normalised_sql", "quality", "question", "source", "tenant_id", "usage_count", "workspace_id"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ExampleRead
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ExampleRead.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ExampleRead is not found in the empty JSON string", ExampleRead.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ExampleRead.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ExampleRead` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ExampleRead.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("created_by").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `created_by` to be a primitive type in the JSON string but got `%s`", jsonObj.get("created_by").toString()));
      }
      if ((jsonObj.get("dataset_id") != null && !jsonObj.get("dataset_id").isJsonNull()) && !jsonObj.get("dataset_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `dataset_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dataset_id").toString()));
      }
      if (!jsonObj.get("generated_sql").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `generated_sql` to be a primitive type in the JSON string but got `%s`", jsonObj.get("generated_sql").toString()));
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("normalised_sql").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `normalised_sql` to be a primitive type in the JSON string but got `%s`", jsonObj.get("normalised_sql").toString()));
      }
      if (!jsonObj.get("quality").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `quality` to be a primitive type in the JSON string but got `%s`", jsonObj.get("quality").toString()));
      }
      // validate the required field `quality`
      QualityEnum.validateJsonElement(jsonObj.get("quality"));
      if (!jsonObj.get("question").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `question` to be a primitive type in the JSON string but got `%s`", jsonObj.get("question").toString()));
      }
      if (!jsonObj.get("source").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `source` to be a primitive type in the JSON string but got `%s`", jsonObj.get("source").toString()));
      }
      // validate the required field `source`
      SourceEnum.validateJsonElement(jsonObj.get("source"));
      if (!jsonObj.get("tenant_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tenant_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tenant_id").toString()));
      }
      if (!jsonObj.get("workspace_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `workspace_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("workspace_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExampleRead.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExampleRead' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExampleRead> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExampleRead.class));

       return (TypeAdapter<T>) new TypeAdapter<ExampleRead>() {
           @Override
           public void write(JsonWriter out, ExampleRead value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ExampleRead read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ExampleRead given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ExampleRead
   * @throws IOException if the JSON string is invalid with respect to ExampleRead
   */
  public static ExampleRead fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExampleRead.class);
  }

  /**
   * Convert an instance of ExampleRead to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

