/*
 * flyquery
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 26.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.firefly.flyquery.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.firefly.flyquery.JSON;

/**
 * Payload for creating a new example (question + SQL pair).
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-23T19:16:18.581048+02:00[Europe/Madrid]", comments = "Generator version: 7.22.0")
public class ExampleCreate {
  public static final String SERIALIZED_NAME_CITATIONS_JSON = "citations_json";
  @SerializedName(SERIALIZED_NAME_CITATIONS_JSON)
  @javax.annotation.Nullable
  private Map<String, Object> citationsJson = new HashMap<>();

  public static final String SERIALIZED_NAME_DATASET_ID = "dataset_id";
  @SerializedName(SERIALIZED_NAME_DATASET_ID)
  @javax.annotation.Nullable
  private UUID datasetId;

  public static final String SERIALIZED_NAME_GENERATED_SQL = "generated_sql";
  @SerializedName(SERIALIZED_NAME_GENERATED_SQL)
  @javax.annotation.Nonnull
  private String generatedSql;

  public static final String SERIALIZED_NAME_QUESTION = "question";
  @SerializedName(SERIALIZED_NAME_QUESTION)
  @javax.annotation.Nonnull
  private String question;

  public ExampleCreate() {
  }

  public ExampleCreate citationsJson(@javax.annotation.Nullable Map<String, Object> citationsJson) {
    this.citationsJson = citationsJson;
    return this;
  }

  public ExampleCreate putCitationsJsonItem(String key, Object citationsJsonItem) {
    if (this.citationsJson == null) {
      this.citationsJson = new HashMap<>();
    }
    this.citationsJson.put(key, citationsJsonItem);
    return this;
  }

  /**
   * Get citationsJson
   * @return citationsJson
   */
  @javax.annotation.Nullable
  public Map<String, Object> getCitationsJson() {
    return citationsJson;
  }

  public void setCitationsJson(@javax.annotation.Nullable Map<String, Object> citationsJson) {
    this.citationsJson = citationsJson;
  }


  public ExampleCreate datasetId(@javax.annotation.Nullable UUID datasetId) {
    this.datasetId = datasetId;
    return this;
  }

  /**
   * Get datasetId
   * @return datasetId
   */
  @javax.annotation.Nullable
  public UUID getDatasetId() {
    return datasetId;
  }

  public void setDatasetId(@javax.annotation.Nullable UUID datasetId) {
    this.datasetId = datasetId;
  }


  public ExampleCreate generatedSql(@javax.annotation.Nonnull String generatedSql) {
    this.generatedSql = generatedSql;
    return this;
  }

  /**
   * Get generatedSql
   * @return generatedSql
   */
  @javax.annotation.Nonnull
  public String getGeneratedSql() {
    return generatedSql;
  }

  public void setGeneratedSql(@javax.annotation.Nonnull String generatedSql) {
    this.generatedSql = generatedSql;
  }


  public ExampleCreate question(@javax.annotation.Nonnull String question) {
    this.question = question;
    return this;
  }

  /**
   * Get question
   * @return question
   */
  @javax.annotation.Nonnull
  public String getQuestion() {
    return question;
  }

  public void setQuestion(@javax.annotation.Nonnull String question) {
    this.question = question;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExampleCreate exampleCreate = (ExampleCreate) o;
    return Objects.equals(this.citationsJson, exampleCreate.citationsJson) &&
        Objects.equals(this.datasetId, exampleCreate.datasetId) &&
        Objects.equals(this.generatedSql, exampleCreate.generatedSql) &&
        Objects.equals(this.question, exampleCreate.question);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(citationsJson, datasetId, generatedSql, question);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExampleCreate {\n");
    sb.append("    citationsJson: ").append(toIndentedString(citationsJson)).append("\n");
    sb.append("    datasetId: ").append(toIndentedString(datasetId)).append("\n");
    sb.append("    generatedSql: ").append(toIndentedString(generatedSql)).append("\n");
    sb.append("    question: ").append(toIndentedString(question)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("citations_json", "dataset_id", "generated_sql", "question"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("generated_sql", "question"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ExampleCreate
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ExampleCreate.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ExampleCreate is not found in the empty JSON string", ExampleCreate.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ExampleCreate.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ExampleCreate` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ExampleCreate.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("dataset_id") != null && !jsonObj.get("dataset_id").isJsonNull()) && !jsonObj.get("dataset_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `dataset_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dataset_id").toString()));
      }
      if (!jsonObj.get("generated_sql").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `generated_sql` to be a primitive type in the JSON string but got `%s`", jsonObj.get("generated_sql").toString()));
      }
      if (!jsonObj.get("question").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `question` to be a primitive type in the JSON string but got `%s`", jsonObj.get("question").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExampleCreate.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExampleCreate' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExampleCreate> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExampleCreate.class));

       return (TypeAdapter<T>) new TypeAdapter<ExampleCreate>() {
           @Override
           public void write(JsonWriter out, ExampleCreate value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ExampleCreate read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ExampleCreate given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ExampleCreate
   * @throws IOException if the JSON string is invalid with respect to ExampleCreate
   */
  public static ExampleCreate fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExampleCreate.class);
  }

  /**
   * Convert an instance of ExampleCreate to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

