# coding: utf-8

"""
    flyquery

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 26.5.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flyquery_sdk.models.semantic_dimension_update import SemanticDimensionUpdate

class TestSemanticDimensionUpdate(unittest.TestCase):
    """SemanticDimensionUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SemanticDimensionUpdate:
        """Test SemanticDimensionUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SemanticDimensionUpdate`
        """
        model = SemanticDimensionUpdate()
        if include_optional:
            return SemanticDimensionUpdate(
                definition_yaml = '',
                description = '',
                label = '',
                metric_type = 'SIMPLE'
            )
        else:
            return SemanticDimensionUpdate(
        )
        """

    def testSemanticDimensionUpdate(self):
        """Test SemanticDimensionUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
