# coding: utf-8

"""
    flyquery

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 26.5.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flyquery_sdk.api.tables_derive_api import TablesDeriveApi


class TestTablesDeriveApi(unittest.IsolatedAsyncioTestCase):
    """TablesDeriveApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = TablesDeriveApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_derive(self) -> None:
        """Test case for derive

        Materialise a SELECT result as a new DERIVED table.
        """
        pass


if __name__ == '__main__':
    unittest.main()
