# coding: utf-8
# Copyright 2024-2026 Firefly Software Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
    flyquery

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 26.5.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from flyquery_sdk.api.semantic_metrics_api import SemanticMetricsApi


class TestSemanticMetricsApi(unittest.IsolatedAsyncioTestCase):
    """SemanticMetricsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SemanticMetricsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create(self) -> None:
        """Test case for create

        Create a new semantic metric in DRAFT status.
        """
        pass

    async def test_get_metric(self) -> None:
        """Test case for get_metric

        Fetch a single semantic metric by id.
        """
        pass

    async def test_history(self) -> None:
        """Test case for history

        Return version history for a metric, oldest first.
        """
        pass

    async def test_list_metrics(self) -> None:
        """Test case for list_metrics

        List all semantic metrics for the caller's workspace.
        """
        pass

    async def test_publish(self) -> None:
        """Test case for publish

        Validate, compile, and publish a metric (status → PUBLISHED).
        """
        pass

    async def test_retire(self) -> None:
        """Test case for retire

        Retire a metric (status → RETIRED).
        """
        pass

    async def test_update(self) -> None:
        """Test case for update

        Sparse-update a metric; re-validates YAML if definition changes.
        """
        pass


if __name__ == '__main__':
    unittest.main()
