# coding: utf-8

"""
    flyquery

    Operational Structured-Data Intelligence (upload-driven) -- multi-tenant ingestion + Text-to-SQL over user-uploaded structured files (CSV / TSV / XLSX / XLS / ODS / JSON / JSONL / Parquet / Avro / ORC / Arrow / Feather + .gz/.zip/.bz2 variants). Materialises uploads to Parquet on object storage; indexes a long-lived schema knowledge base; answers natural-language questions via a multi-agent pipeline. Part of Firefly OperationOS.

    The version of the OpenAPI document: 26.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SemanticVersionRead(BaseModel):
    """
    Read representation of a flyquery_semantic_versions row.  Field names follow the documented payload (``version_number``, ``metric_id``); the underlying columns are ``version`` / ``parent_id`` and are mapped via validation aliases.
    """ # noqa: E501
    compiled_sql_template: Optional[StrictStr]
    created_at: datetime
    created_by: StrictStr
    definition_yaml: StrictStr
    id: UUID
    kind: StrictStr
    parent_id: UUID
    tenant_id: StrictStr
    version: StrictInt
    workspace_id: UUID
    __properties: ClassVar[List[str]] = ["compiled_sql_template", "created_at", "created_by", "definition_yaml", "id", "kind", "parent_id", "tenant_id", "version", "workspace_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SemanticVersionRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if compiled_sql_template (nullable) is None
        # and model_fields_set contains the field
        if self.compiled_sql_template is None and "compiled_sql_template" in self.model_fields_set:
            _dict['compiled_sql_template'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SemanticVersionRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "compiled_sql_template": obj.get("compiled_sql_template"),
            "created_at": obj.get("created_at"),
            "created_by": obj.get("created_by"),
            "definition_yaml": obj.get("definition_yaml"),
            "id": obj.get("id"),
            "kind": obj.get("kind"),
            "parent_id": obj.get("parent_id"),
            "tenant_id": obj.get("tenant_id"),
            "version": obj.get("version"),
            "workspace_id": obj.get("workspace_id")
        })
        return _obj


