# coding: utf-8

"""
    flyquery

    Operational Structured-Data Intelligence (upload-driven) -- multi-tenant ingestion + Text-to-SQL over user-uploaded structured files (CSV / TSV / XLSX / XLS / ODS / JSON / JSONL / Parquet / Avro / ORC / Arrow / Feather + .gz/.zip/.bz2 variants). Materialises uploads to Parquet on object storage; indexes a long-lived schema knowledge base; answers natural-language questions via a multi-agent pipeline. Part of Firefly OperationOS.

    The version of the OpenAPI document: 26.5.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TableRead(BaseModel):
    """
    Response for GET /tables/{id}.
    """ # noqa: E501
    business_owner: Optional[StrictStr]
    created_at: datetime
    current_snapshot_id: Optional[UUID]
    dataset_id: UUID
    description: Optional[StrictStr]
    description_source: Optional[StrictStr]
    id: UUID
    is_active: StrictBool
    kind: StrictStr
    n_columns: Optional[StrictInt] = None
    name: StrictStr
    qualified_name: StrictStr
    sheet_or_json_path: Optional[StrictStr]
    source_file_id: Optional[UUID]
    tenant_id: StrictStr
    updated_at: datetime
    workspace_id: UUID
    __properties: ClassVar[List[str]] = ["business_owner", "created_at", "current_snapshot_id", "dataset_id", "description", "description_source", "id", "is_active", "kind", "n_columns", "name", "qualified_name", "sheet_or_json_path", "source_file_id", "tenant_id", "updated_at", "workspace_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TableRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if business_owner (nullable) is None
        # and model_fields_set contains the field
        if self.business_owner is None and "business_owner" in self.model_fields_set:
            _dict['business_owner'] = None

        # set to None if current_snapshot_id (nullable) is None
        # and model_fields_set contains the field
        if self.current_snapshot_id is None and "current_snapshot_id" in self.model_fields_set:
            _dict['current_snapshot_id'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if description_source (nullable) is None
        # and model_fields_set contains the field
        if self.description_source is None and "description_source" in self.model_fields_set:
            _dict['description_source'] = None

        # set to None if n_columns (nullable) is None
        # and model_fields_set contains the field
        if self.n_columns is None and "n_columns" in self.model_fields_set:
            _dict['n_columns'] = None

        # set to None if sheet_or_json_path (nullable) is None
        # and model_fields_set contains the field
        if self.sheet_or_json_path is None and "sheet_or_json_path" in self.model_fields_set:
            _dict['sheet_or_json_path'] = None

        # set to None if source_file_id (nullable) is None
        # and model_fields_set contains the field
        if self.source_file_id is None and "source_file_id" in self.model_fields_set:
            _dict['source_file_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TableRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "business_owner": obj.get("business_owner"),
            "created_at": obj.get("created_at"),
            "current_snapshot_id": obj.get("current_snapshot_id"),
            "dataset_id": obj.get("dataset_id"),
            "description": obj.get("description"),
            "description_source": obj.get("description_source"),
            "id": obj.get("id"),
            "is_active": obj.get("is_active"),
            "kind": obj.get("kind"),
            "n_columns": obj.get("n_columns"),
            "name": obj.get("name"),
            "qualified_name": obj.get("qualified_name"),
            "sheet_or_json_path": obj.get("sheet_or_json_path"),
            "source_file_id": obj.get("source_file_id"),
            "tenant_id": obj.get("tenant_id"),
            "updated_at": obj.get("updated_at"),
            "workspace_id": obj.get("workspace_id")
        })
        return _obj


