/*
 * flyquery
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 26.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.firefly.flyquery.api;

import io.firefly.flyquery.ApiException;
import io.firefly.flyquery.model.GlossaryTermCreate;
import io.firefly.flyquery.model.GlossaryTermRead;
import io.firefly.flyquery.model.GlossaryTermUpdate;
import io.firefly.flyquery.model.HTTPValidationError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GlossaryApi
 */
@Disabled
public class GlossaryApiTest {

    private final GlossaryApi api = new GlossaryApi();

    /**
     * Create a glossary term; (workspace_id, term) must be unique.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTest() throws ApiException {
        GlossaryTermCreate glossaryTermCreate = null;
        GlossaryTermRead response = api.create(glossaryTermCreate);
        // TODO: test validations
    }

    /**
     * Hard-delete a glossary term.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteTest() throws ApiException {
        String termId = null;
        api.delete(termId);
        // TODO: test validations
    }

    /**
     * Return paginated glossary terms for the caller&#39;s workspace.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTermsTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        api.listTerms(limit, offset);
        // TODO: test validations
    }

    /**
     * Sparse-update a glossary term.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTest() throws ApiException {
        String termId = null;
        GlossaryTermUpdate glossaryTermUpdate = null;
        GlossaryTermRead response = api.update(termId, glossaryTermUpdate);
        // TODO: test validations
    }

}
